import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { randomUUID } from 'node:crypto';
import { prisma } from '../../db/prisma';
import { authGuard } from '../../middlewares/auth';
import { attachmentCommitSchema, attachmentUploadSchema, closeSchema, complaintCreateSchema, complaintMessageSchema, escalateSchema, officerAssignSchema, officerReplySchema, pageSchema, trackingSecretSchema } from './stage4.validators';
import { accessAudit, addBusinessMinutes, createNeutralNotification, hashSecret, safeEvent, trackingCode, trackingSecret, verifySecret } from './stage4.shared';
import { complaintDto } from './stage4.presenter';
import { assertStorageReady } from '../voiceNotes/storage.service';
import { attachmentKey, cleanupObject, downloadUrl, uploadUrl, validateAttachment, verifyAttachmentObject } from './stage4.storage';

function role(req:FastifyRequest,reply:FastifyReply,allowed:string[]){if(!req.user||!allowed.includes(req.user.role)){void reply.code(403).send({message:'Forbidden'});return false}return true}
async function optionalUser(req:FastifyRequest){try{await req.jwtVerify();const p=req.user;if(!p?.userId||p?.tokenUse!=='ACCESS'||!p?.sessionId)return null;const u=await prisma.users.findUnique({where:{id:p.userId},select:{id:true,role:true,is_active:true,session_version:true,display_alias:true}});if(!u?.is_active||u.session_version!==p.sessionVersion)return null;return u}catch{return null}}
async function ownTicket(publicId:string,userId:string){return prisma.complaint_tickets.findFirst({where:{public_id:publicId,user_id:userId}})}
async function officerTicket(publicId:string,user:any){return prisma.complaint_tickets.findFirst({where:{public_id:publicId,...(user.role==='SUPERVISOR'?{escalation_level:{gt:0}}:{assigned_officer_id:user.userId})}})}
async function slaConfig(category:any,priority:number){return(await prisma.complaint_sla_configs.findFirst({where:{is_active:true,OR:[{category,priority},{category:null,priority:null}]},orderBy:[{category:'desc'},{priority:'desc'}]}))!}
async function fullTicket(id:string,includeInternal=false){const t=await prisma.complaint_tickets.findUnique({where:{id},include:{officer:{select:{public_id:true,full_name:true}},messages:{where:includeInternal?{}:{type:{not:'INTERNAL_NOTE'}},orderBy:{created_at:'asc'}},events:{orderBy:{created_at:'asc'}},attachments:{where:{deleted_at:null},orderBy:{created_at:'asc'}}}});if(!t)return null;const cfg=await slaConfig(t.category,t.priority);return Object.assign(t,{sla_timezone:cfg?.timezone??'Asia/Jayapura'})}
async function updateStatus(ticket:any,actor:any,status:any,event:string,data:any={}){const now=new Date();const updated=await prisma.complaint_tickets.update({where:{id:ticket.id},data:{status,...data,updated_at:now}});await safeEvent('complaint',ticket.id,event,actor?.userId??null);if(ticket.user_id)await createNeutralNotification(ticket.user_id,`complaint:${ticket.public_id}:${event}:${updated.updated_at.getTime()}`,'COMPLAINT_UPDATE',ticket.public_id,'Anda memiliki pembaruan baru.');return updated}
async function trackedTicket(code:string,rawSecret:unknown){const parsed=trackingSecretSchema.safeParse(rawSecret);if(!parsed.success)return null;const ticket=await prisma.complaint_tickets.findUnique({where:{tracking_code:code}});return ticket&&await verifySecret(parsed.data,ticket.tracking_secret_hash)?ticket:null}

export default async function complaintsRoutes(app:FastifyInstance){
 app.post('/complaints',{config:{rateLimit:{max:5,timeWindow:'1 hour'}}},async(req,reply)=>{const user=await optionalUser(req);const b=complaintCreateSchema.parse(req.body);if(b.facility_id){const facility=await prisma.health_facilities.findFirst({where:{id:b.facility_id,verification_status:'VERIFIED',is_active:true}});if(!facility)return reply.code(400).send({message:'Facility unavailable'})}const existing=await prisma.complaint_tickets.findUnique({where:{submission_key:b.submission_key}});if(existing)return reply.code(409).send({message:'Submission already received'});const config=await slaConfig(b.category,b.priority);if(!config)return reply.code(503).send({message:'Complaint service unavailable'});const now=new Date();const secret=trackingSecret();const code=trackingCode();const secretHash=await hashSecret(secret);const common={active_days:config.active_days,opens_at:config.opens_at,closes_at:config.closes_at,timezone:config.timezone};const t=await prisma.complaint_tickets.create({data:{id:randomUUID(),tracking_code:code,tracking_secret_hash:secretHash,user_id:b.privacy_level==='PRIVATE'&&user?.role==='PASIEN'?user.id:null,alias_snapshot:b.privacy_level==='PRIVATE'?user?.display_alias??null:null,category:b.category,subject:b.subject,description:b.description,priority:b.priority,facility_id:b.facility_id??null,privacy_level:b.privacy_level,consented_at:now,submission_key:b.submission_key,acknowledgement_due_at:addBusinessMinutes(now,config.acknowledgement_minutes,common),response_due_at:addBusinessMinutes(now,config.response_minutes,common),resolution_due_at:addBusinessMinutes(now,config.resolution_minutes,common),updated_at:now}});await safeEvent('complaint',t.id,'SUBMITTED',user?.id??null,{category:b.category,priority:b.priority});return reply.code(201).send({...complaintDto(Object.assign(t,{sla_timezone:config.timezone})),tracking_secret:secret,tracking_secret_notice:'Simpan kode ini. Kode hanya ditampilkan sekali.'})});
 app.get('/complaints',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN']))return;const p=pageSchema.parse(req.query);const where:any={user_id:req.user!.userId,...(p.status?{status:p.status as any}:{})};const[rows,total]=await Promise.all([prisma.complaint_tickets.findMany({where,orderBy:{created_at:'desc'},skip:(p.page-1)*p.limit,take:p.limit}),prisma.complaint_tickets.count({where})]);return{items:rows.map(t=>complaintDto(t)),page:p.page,total}});
 app.get('/complaints/track/:trackingCode',{config:{rateLimit:{max:10,timeWindow:'10 minutes'}}},async(req,reply)=>{const secret=trackingSecretSchema.safeParse(req.headers['x-tracking-secret']);if(!secret.success)return reply.code(401).send({message:'Invalid tracking credentials'});const t=await prisma.complaint_tickets.findUnique({where:{tracking_code:(req.params as any).trackingCode}});if(!t||!await verifySecret(secret.data,t.tracking_secret_hash))return reply.code(404).send({message:'Ticket not found'});await accessAudit({resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:'TRACK',correlationId:req.id});return complaintDto(await fullTicket(t.id,false),true,false)});
 app.get('/complaints/:publicId',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN']))return;const t=await ownTicket((req.params as any).publicId,req.user!.userId);if(!t)return reply.code(404).send({message:'Not found'});await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:'OPEN',correlationId:req.id});return complaintDto(await fullTicket(t.id,false),true,false)});
 app.post('/complaints/:publicId/messages',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN']))return;const t=await ownTicket((req.params as any).publicId,req.user!.userId);if(!t)return reply.code(404).send({message:'Not found'});if(['CLOSED','REJECTED'].includes(t.status))return reply.code(409).send({message:'Ticket is closed'});const b=complaintMessageSchema.parse(req.body);const existing=await prisma.complaint_messages.findFirst({where:{ticket_id:t.id,sender_user_id:req.user!.userId,idempotency_key:b.idempotency_key}});if(existing)return{public_id:existing.public_id,type:existing.type,content:existing.content,created_at:existing.created_at};const m=await prisma.complaint_messages.create({data:{id:randomUUID(),ticket_id:t.id,sender_user_id:req.user!.userId,sender_role:'PASIEN',type:'PUBLIC_REPLY',content:b.content,idempotency_key:b.idempotency_key}});await updateStatus(t,req.user!,'IN_REVIEW','USER_REPLIED');return reply.code(201).send({public_id:m.public_id,type:m.type,content:m.content,created_at:m.created_at})});
 app.post('/complaints/:publicId/close',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN']))return;const t=await ownTicket((req.params as any).publicId,req.user!.userId);if(!t)return reply.code(404).send({message:'Not found'});closeSchema.parse(req.body??{});return complaintDto(await updateStatus(t,req.user!,'CLOSED','CLOSED_BY_USER',{closed_at:new Date()}))});

 app.get('/complaint-admin/queue',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['COMPLAINT_OFFICER','SUPERVISOR','ADMIN']))return;const p=pageSchema.parse(req.query);const where:any={...(req.user!.role==='COMPLAINT_OFFICER'?{OR:[{assigned_officer_id:null},{assigned_officer_id:req.user!.userId}]}:{}),...(req.user!.role==='SUPERVISOR'?{escalation_level:{gt:0}}:{}),...(p.status?{status:p.status as any}:{})};const rows=await prisma.complaint_tickets.findMany({where,orderBy:[{priority:'desc'},{created_at:'asc'}],skip:(p.page-1)*p.limit,take:p.limit,select:{public_id:true,category:true,priority:true,status:true,created_at:true,response_due_at:true,resolution_due_at:true,escalation_level:true,assigned_officer_id:true}});return{items:rows.map(x=>({...x,assigned:Boolean(x.assigned_officer_id)})),page:p.page}});
 app.get('/complaint-admin/:publicId',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['COMPLAINT_OFFICER','SUPERVISOR']))return;const t=await officerTicket((req.params as any).publicId,req.user!);if(!t)return reply.code(404).send({message:'Not found'});await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:'OPEN_INTERNAL',correlationId:req.id});return complaintDto(await fullTicket(t.id,true),true,true)});
 async function assign(req:FastifyRequest,reply:FastifyReply,reassign=false){if(!role(req,reply,['COMPLAINT_OFFICER','SUPERVISOR','ADMIN']))return;const b=officerAssignSchema.parse(req.body??{});let officer:any;if(req.user!.role==='COMPLAINT_OFFICER'){if(b.officer_public_id)return reply.code(403).send({message:'Officer cannot select another officer'});officer=await prisma.users.findUnique({where:{id:req.user!.userId}})}else{if(!b.officer_public_id)return reply.code(400).send({message:'Officer required'});officer=await prisma.users.findUnique({where:{public_id:b.officer_public_id}})}if(!officer?.is_active||officer.role!=='COMPLAINT_OFFICER')return reply.code(400).send({message:'Officer unavailable'});const t=await prisma.complaint_tickets.findUnique({where:{public_id:(req.params as any).publicId}});if(!t)return reply.code(404).send({message:'Not found'});const now=new Date();const updated=await prisma.$transaction(async tx=>{const changed=await tx.complaint_tickets.updateMany({where:{id:t.id,...(reassign?{assigned_officer_id:t.assigned_officer_id}:{assigned_officer_id:null}),status:{notIn:['CLOSED','REJECTED']}},data:{assigned_officer_id:officer.id,assigned_at:now,status:'ASSIGNED',updated_at:now}});if(!changed.count)return null;if(reassign)await tx.complaint_assignments.updateMany({where:{ticket_id:t.id,status:'ACTIVE'},data:{status:'ENDED',unassigned_at:now,unassignment_reason:b.reason??'REASSIGNED'}});await tx.complaint_assignments.create({data:{id:randomUUID(),ticket_id:t.id,officer_id:officer.id,assigned_by:req.user!.userId,source:req.user!.role==='COMPLAINT_OFFICER'?'SELF_CLAIM':'MANUAL'}});return tx.complaint_tickets.findUnique({where:{id:t.id}})});if(!updated)return reply.code(409).send({message:'Ticket already claimed'});await safeEvent('complaint',t.id,reassign?'REASSIGNED':'ASSIGNED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:reassign?'REASSIGN':'ASSIGN',correlationId:req.id});if(t.user_id)await createNeutralNotification(t.user_id,`complaint:${t.public_id}:assigned:${now.getTime()}`,'COMPLAINT_UPDATE',t.public_id,'Anda memiliki pembaruan baru.');return complaintDto(updated)}
 app.post('/complaint-admin/:publicId/assign',{preHandler:[authGuard]},(req,reply)=>assign(req,reply,false));
 app.post('/complaint-admin/:publicId/reassign',{preHandler:[authGuard]},async(req,reply)=>{const body=officerAssignSchema.parse(req.body??{});if(!body.reason)return reply.code(400).send({message:'Alasan reassignment wajib diisi'});return assign(req,reply,true)});
 app.post('/complaint-admin/:publicId/acknowledge',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['COMPLAINT_OFFICER']))return;const t=await officerTicket((req.params as any).publicId,req.user!);if(!t)return reply.code(404).send({message:'Not found'});return complaintDto(await updateStatus(t,req.user!,'ACKNOWLEDGED','ACKNOWLEDGED',{acknowledged_at:new Date()}))});
 async function officerMessage(req:FastifyRequest,reply:FastifyReply,type:'PUBLIC_REPLY'|'INTERNAL_NOTE'){if(!role(req,reply,['COMPLAINT_OFFICER','SUPERVISOR']))return;const t=await officerTicket((req.params as any).publicId,req.user!);if(!t)return reply.code(404).send({message:'Not found'});const b=officerReplySchema.parse(req.body);const existing=await prisma.complaint_messages.findFirst({where:{ticket_id:t.id,sender_user_id:req.user!.userId,idempotency_key:b.idempotency_key}});if(existing)return{public_id:existing.public_id,type:existing.type,created_at:existing.created_at};const m=await prisma.complaint_messages.create({data:{id:randomUUID(),ticket_id:t.id,sender_user_id:req.user!.userId,sender_role:req.user!.role as any,type,content:b.content,idempotency_key:b.idempotency_key}});await safeEvent('complaint',t.id,type==='PUBLIC_REPLY'?'PUBLIC_REPLY':'INTERNAL_NOTE_ADDED',req.user!.userId);if(type==='INTERNAL_NOTE')await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:'INTERNAL_NOTE_CREATE',correlationId:req.id});else{await prisma.complaint_tickets.update({where:{id:t.id},data:{status:'WAITING_USER',responded_at:new Date(),updated_at:new Date()}});if(t.user_id)await createNeutralNotification(t.user_id,`complaint-msg:${m.public_id}`,'COMPLAINT_UPDATE',t.public_id,'Anda memiliki pembaruan baru.')}return reply.code(201).send({public_id:m.public_id,type:m.type,created_at:m.created_at})}
 app.post('/complaint-admin/:publicId/reply',{preHandler:[authGuard]},(req,reply)=>officerMessage(req,reply,'PUBLIC_REPLY'));
 app.post('/complaint-admin/:publicId/internal-note',{preHandler:[authGuard]},(req,reply)=>officerMessage(req,reply,'INTERNAL_NOTE'));
 app.post('/complaint-admin/:publicId/resolve',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['COMPLAINT_OFFICER']))return;const t=await officerTicket((req.params as any).publicId,req.user!);if(!t)return reply.code(404).send({message:'Not found'});return complaintDto(await updateStatus(t,req.user!,'RESOLVED','RESOLVED',{resolved_at:new Date()}))});
 app.post('/complaint-admin/:publicId/close',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['COMPLAINT_OFFICER','SUPERVISOR']))return;const t=await officerTicket((req.params as any).publicId,req.user!);if(!t)return reply.code(404).send({message:'Not found'});return complaintDto(await updateStatus(t,req.user!,'CLOSED','CLOSED',{closed_at:new Date()}))});
 app.post('/complaint-admin/:publicId/escalate',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['COMPLAINT_OFFICER','SUPERVISOR']))return;const t=await officerTicket((req.params as any).publicId,req.user!);if(!t)return reply.code(404).send({message:'Not found'});const b=escalateSchema.parse(req.body);const updated=await updateStatus(t,req.user!,'ESCALATED','ESCALATED',{escalation_level:{increment:1}});await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:'ESCALATE',correlationId:req.id,reason:b.reason});return complaintDto(updated)});

 app.post('/complaints/:publicId/attachments/upload-url',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN']))return;const t=await ownTicket((req.params as any).publicId,req.user!.userId);if(!t)return reply.code(404).send({message:'Not found'});const b=attachmentUploadSchema.parse(req.body);try{validateAttachment(b.content_type,b.file_size_bytes)}catch{return reply.code(400).send({message:'Invalid attachment metadata'})}if(await prisma.complaint_attachments.count({where:{ticket_id:t.id,deleted_at:null}})>=5)return reply.code(409).send({message:'Attachment limit reached'});await assertStorageReady();const key=attachmentKey();const s=await prisma.complaint_attachment_upload_sessions.create({data:{id:randomUUID(),ticket_id:t.id,requested_by:req.user!.userId,storage_key:key,content_type:b.content_type,file_size_bytes:b.file_size_bytes,expires_at:new Date(Date.now()+5*60_000)}});return{upload_session_id:s.id,upload_url:await uploadUrl(key,b.content_type),expires_at:s.expires_at}});
 app.post('/complaints/:publicId/attachments/commit',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN']))return;const t=await ownTicket((req.params as any).publicId,req.user!.userId);if(!t)return reply.code(404).send({message:'Not found'});const b=attachmentCommitSchema.parse(req.body);const s=await prisma.complaint_attachment_upload_sessions.findUnique({where:{id:b.upload_session_id}});if(!s||s.ticket_id!==t.id||s.requested_by!==req.user!.userId||s.committed_at)return reply.code(400).send({message:'Upload session invalid'});if(s.expires_at<new Date()){await cleanupObject(s.storage_key);return reply.code(400).send({message:'Upload session expired'})}try{await verifyAttachmentObject(s.storage_key,b.content_type,b.file_size_bytes)}catch{await cleanupObject(s.storage_key);return reply.code(400).send({message:'Invalid attachment'})}try{const a=await prisma.$transaction(async tx=>{const marked=await tx.complaint_attachment_upload_sessions.updateMany({where:{id:s.id,committed_at:null},data:{committed_at:new Date()}});if(!marked.count)throw new Error('Already committed');return tx.complaint_attachments.create({data:{id:randomUUID(),ticket_id:t.id,uploaded_by:req.user!.userId,storage_key:s.storage_key,content_type:b.content_type,file_size_bytes:b.file_size_bytes}})});await safeEvent('complaint',t.id,'ATTACHMENT_ADDED',req.user!.userId);return reply.code(201).send({public_id:a.public_id,content_type:a.content_type,file_size_bytes:a.file_size_bytes})}catch(e){await cleanupObject(s.storage_key);throw e}});
 app.get('/complaint-attachments/:publicId',{preHandler:[authGuard]},async(req,reply)=>{if(!role(req,reply,['PASIEN','COMPLAINT_OFFICER','SUPERVISOR']))return;const a=await prisma.complaint_attachments.findUnique({where:{public_id:(req.params as any).publicId},include:{ticket:true}});if(!a||a.deleted_at||a.quarantine_status!=='CLEAN')return reply.code(404).send({message:'Not found'});const allowed=req.user!.role==='PASIEN'?a.ticket.user_id===req.user!.userId:a.ticket.assigned_officer_id===req.user!.userId||(req.user!.role==='SUPERVISOR'&&a.ticket.escalation_level>0);if(!allowed)return reply.code(404).send({message:'Not found'});await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT_ATTACHMENT',resourcePublicId:a.public_id,action:'DOWNLOAD',correlationId:req.id});return{public_id:a.public_id,content_type:a.content_type,file_size_bytes:a.file_size_bytes,download_url:await downloadUrl(a.storage_key)}});
 app.post('/complaints/track/:trackingCode/messages',{config:{rateLimit:{max:20,timeWindow:'10 minutes'}}},async(req,reply)=>{const t=await trackedTicket((req.params as any).trackingCode,req.headers['x-tracking-secret']);if(!t)return reply.code(404).send({message:'Ticket not found'});if(['CLOSED','REJECTED'].includes(t.status))return reply.code(409).send({message:'Ticket is closed'});const b=complaintMessageSchema.parse(req.body);const existing=await prisma.complaint_messages.findFirst({where:{ticket_id:t.id,sender_user_id:null,idempotency_key:b.idempotency_key}});if(existing)return{public_id:existing.public_id,type:existing.type,created_at:existing.created_at};const m=await prisma.complaint_messages.create({data:{id:randomUUID(),ticket_id:t.id,sender_user_id:null,sender_role:'PASIEN',type:'PUBLIC_REPLY',content:b.content,idempotency_key:b.idempotency_key}});await updateStatus(t,null,'IN_REVIEW','ANONYMOUS_USER_REPLIED');return reply.code(201).send({public_id:m.public_id,type:m.type,created_at:m.created_at})});
 app.post('/complaints/track/:trackingCode/attachments/upload-url',{config:{rateLimit:{max:10,timeWindow:'10 minutes'}}},async(req,reply)=>{const t=await trackedTicket((req.params as any).trackingCode,req.headers['x-tracking-secret']);if(!t)return reply.code(404).send({message:'Ticket not found'});const b=attachmentUploadSchema.parse(req.body);try{validateAttachment(b.content_type,b.file_size_bytes)}catch{return reply.code(400).send({message:'Invalid attachment metadata'})}if(await prisma.complaint_attachments.count({where:{ticket_id:t.id,deleted_at:null}})>=5)return reply.code(409).send({message:'Attachment limit reached'});await assertStorageReady();const storageKey=attachmentKey();const s=await prisma.complaint_attachment_upload_sessions.create({data:{id:randomUUID(),ticket_id:t.id,requested_by:null,storage_key:storageKey,content_type:b.content_type,file_size_bytes:b.file_size_bytes,expires_at:new Date(Date.now()+5*60_000)}});return{upload_session_id:s.id,upload_url:await uploadUrl(storageKey,b.content_type),expires_at:s.expires_at}});
 app.post('/complaints/track/:trackingCode/attachments/commit',async(req,reply)=>{const t=await trackedTicket((req.params as any).trackingCode,req.headers['x-tracking-secret']);if(!t)return reply.code(404).send({message:'Ticket not found'});const b=attachmentCommitSchema.parse(req.body);const s=await prisma.complaint_attachment_upload_sessions.findUnique({where:{id:b.upload_session_id}});if(!s||s.ticket_id!==t.id||s.requested_by!==null||s.committed_at)return reply.code(400).send({message:'Upload session invalid'});if(s.expires_at<new Date()){await cleanupObject(s.storage_key);return reply.code(400).send({message:'Upload session expired'})}try{await verifyAttachmentObject(s.storage_key,b.content_type,b.file_size_bytes)}catch{await cleanupObject(s.storage_key);return reply.code(400).send({message:'Invalid attachment'})}const a=await prisma.$transaction(async tx=>{const marked=await tx.complaint_attachment_upload_sessions.updateMany({where:{id:s.id,committed_at:null},data:{committed_at:new Date()}});if(!marked.count)throw new Error('Already committed');return tx.complaint_attachments.create({data:{id:randomUUID(),ticket_id:t.id,uploaded_by:null,storage_key:s.storage_key,content_type:b.content_type,file_size_bytes:b.file_size_bytes}})});await safeEvent('complaint',t.id,'ATTACHMENT_ADDED',null);return reply.code(201).send({public_id:a.public_id,content_type:a.content_type,file_size_bytes:a.file_size_bytes})});
 app.get('/complaints/track/:trackingCode/attachments/:attachmentId',async(req,reply)=>{const p=req.params as any;const t=await trackedTicket(p.trackingCode,req.headers['x-tracking-secret']);if(!t)return reply.code(404).send({message:'Ticket not found'});const a=await prisma.complaint_attachments.findFirst({where:{public_id:p.attachmentId,ticket_id:t.id,deleted_at:null,quarantine_status:'CLEAN'}});if(!a)return reply.code(404).send({message:'Not found'});await accessAudit({resourceType:'COMPLAINT_ATTACHMENT',resourcePublicId:a.public_id,action:'ANONYMOUS_DOWNLOAD',correlationId:req.id});return{public_id:a.public_id,content_type:a.content_type,file_size_bytes:a.file_size_bytes,download_url:await downloadUrl(a.storage_key)}});
}
