import{FastifyInstance,FastifyReply,FastifyRequest}from'fastify';import{z}from'zod';import{prisma}from'../../db/prisma';import{authGuard}from'../../middlewares/auth';import{env}from'../../config/env';import{accessAudit,safeEvent}from'./stage4.shared';
const reasonSchema=z.object({reason:z.string().trim().min(8).max(500).refine(v=>!/[<>\u0000-\u001f]/.test(v),'Unsafe reason')}).strict();
function supervisor(req:FastifyRequest,reply:FastifyReply){if(req.user?.role!=='SUPERVISOR'){void reply.code(403).send({message:'Forbidden'});return false}return true}
export default async function governanceRoutes(app:FastifyInstance){
 app.get('/stage4-governance/policy',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;return{retention_days:env.STAGE4_RETENTION_DAYS,retention_mode:env.STAGE4_RETENTION_MODE,legal_hold_enabled:env.STAGE4_LEGAL_HOLD_ENABLED,automatic_deletion:false,user_deletion_request:'REVIEW_REQUIRED'}});
 app.get('/stage4-governance/audits',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const q=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(20)}).parse(req.query);const rows=await prisma.sensitive_access_audits.findMany({orderBy:{created_at:'desc'},skip:(q.page-1)*q.limit,take:q.limit,select:{resource_type:true,resource_public_id:true,action:true,result:true,actor_role:true,reason:true,correlation_id:true,safe_metadata:true,created_at:true}});return{items:rows,page:q.page}});
 app.post('/stage4-governance/conversations/:publicId/archive',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const b=reasonSchema.parse(req.body);const c=await prisma.service_conversations.findUnique({where:{public_id:(req.params as any).publicId}});if(!c)return reply.code(404).send({message:'Not found'});await prisma.service_conversations.update({where:{id:c.id},data:{retention_status:'ARCHIVED',archived_at:new Date(),updated_at:new Date()}});await safeEvent('conversation',c.id,'ARCHIVED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'SERVICE_CONVERSATION',resourcePublicId:c.public_id,action:'ARCHIVE',reason:b.reason,correlationId:req.id});return{public_id:c.public_id,retention_status:'ARCHIVED'}});
 app.post('/stage4-governance/conversations/:publicId/restrict',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const b=reasonSchema.parse(req.body);const c=await prisma.service_conversations.findUnique({where:{public_id:(req.params as any).publicId}});if(!c)return reply.code(404).send({message:'Not found'});await prisma.service_conversations.update({where:{id:c.id},data:{retention_status:'RESTRICTED',restricted_at:new Date(),updated_at:new Date()}});await safeEvent('conversation',c.id,'RESTRICTED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'SERVICE_CONVERSATION',resourcePublicId:c.public_id,action:'RESTRICT',reason:b.reason,correlationId:req.id});return{public_id:c.public_id,retention_status:'RESTRICTED'}});
 app.post('/stage4-governance/messages/:publicId/redact',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const b=reasonSchema.parse(req.body);const m=await prisma.service_messages.findUnique({where:{public_id:(req.params as any).publicId},include:{conversation:true}});if(!m)return reply.code(404).send({message:'Not found'});await prisma.$transaction(async tx=>{await tx.service_messages.update({where:{id:m.id},data:{content:null,redacted_at:new Date(),redaction_reason:b.reason,updated_at:new Date()}});if(m.voice_note_id)await tx.conversation_voice_notes.update({where:{id:m.voice_note_id},data:{deleted_at:new Date()}})});await safeEvent('conversation',m.conversation_id,'MESSAGE_REDACTED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'SERVICE_MESSAGE',resourcePublicId:m.public_id,action:'REDACT',reason:b.reason,correlationId:req.id});return{public_id:m.public_id,redacted:true}});
 app.post('/stage4-governance/complaints/:publicId/:operation',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const b=reasonSchema.parse(req.body);const p=req.params as any;if(!['archive','restrict'].includes(p.operation))return reply.code(404).send({message:'Not found'});const t=await prisma.complaint_tickets.findUnique({where:{public_id:p.publicId}});if(!t)return reply.code(404).send({message:'Not found'});const archive=p.operation==='archive';await prisma.complaint_tickets.update({where:{id:t.id},data:{retention_status:archive?'ARCHIVED':'RESTRICTED',...(archive?{archived_at:new Date()}:{restricted_at:new Date()}),updated_at:new Date()}});await safeEvent('complaint',t.id,archive?'ARCHIVED':'RESTRICTED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT',resourcePublicId:t.public_id,action:archive?'ARCHIVE':'RESTRICT',reason:b.reason,correlationId:req.id});return{public_id:t.public_id,retention_status:archive?'ARCHIVED':'RESTRICTED'}});
 app.post('/stage4-governance/complaint-messages/:publicId/redact',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const b=reasonSchema.parse(req.body);const m=await prisma.complaint_messages.findUnique({where:{public_id:(req.params as any).publicId}});if(!m)return reply.code(404).send({message:'Not found'});await prisma.complaint_messages.update({where:{id:m.id},data:{content:'',redacted_at:new Date(),redaction_reason:b.reason}});await safeEvent('complaint',m.ticket_id,'MESSAGE_REDACTED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT_MESSAGE',resourcePublicId:m.public_id,action:'REDACT',reason:b.reason,correlationId:req.id});return{public_id:m.public_id,redacted:true}});
 app.post('/stage4-governance/attachments/:publicId/quarantine',{preHandler:[authGuard]},async(req,reply)=>{if(!supervisor(req,reply))return;const b=reasonSchema.parse(req.body);const a=await prisma.complaint_attachments.findUnique({where:{public_id:(req.params as any).publicId}});if(!a)return reply.code(404).send({message:'Not found'});await prisma.complaint_attachments.update({where:{id:a.id},data:{quarantine_status:'QUARANTINED'}});await safeEvent('complaint',a.ticket_id,'ATTACHMENT_QUARANTINED',req.user!.userId);await accessAudit({actorId:req.user!.userId,actorRole:req.user!.role,resourceType:'COMPLAINT_ATTACHMENT',resourcePublicId:a.public_id,action:'QUARANTINE',reason:b.reason,correlationId:req.id});return{public_id:a.public_id,quarantine_status:'QUARANTINED'}});
 app.post('/stage4-data-deletion-requests',{preHandler:[authGuard]},async(req,reply)=>{if(req.user?.role!=='PASIEN')return reply.code(403).send({message:'Forbidden'});const b=reasonSchema.parse(req.body);const user=await prisma.users.findUniqueOrThrow({where:{id:req.user.userId},select:{public_id:true}});await accessAudit({actorId:req.user.userId,actorRole:req.user.role,resourceType:'USER_DATA',resourcePublicId:user.public_id,action:'DELETION_REQUEST',reason:b.reason,correlationId:req.id,safeMetadata:{status:'REVIEW_REQUIRED'}});return reply.code(202).send({status:'REVIEW_REQUIRED',message:'Permintaan tercatat. Histori layanan mengikuti kebijakan retensi institusi.'})});
}
