import { FormEvent, useEffect, useState } from 'react';
import { changePasswordRequest, convertAnonymousRequest, getAccountProfileRequest, logoutAllRequest, regenerateRecoveryRequest, updateAccountProfileRequest, type AccountProfile, type AnonymousCredentials } from '../api/client';
import { useAuth } from '../context/AuthContext';
import { usePrivacy } from '../context/PrivacyContext';
import { Button } from '../components/ui/button'; import { Input } from '../components/ui/input'; import { Label } from '../components/ui/label'; import { CredentialsPanel } from './AnonymousRegistrationPage';

export function AccountProfilePage() {
 const {token,logout}=useAuth(); const {preferences,updatePreferences}=usePrivacy(); const [profile,setProfile]=useState<AccountProfile|null>(null); const [alias,setAlias]=useState(''); const [message,setMessage]=useState(''); const [secret,setSecret]=useState(''); const [credentials,setCredentials]=useState<AnonymousCredentials|null>(null); const [loginIdCopied,setLoginIdCopied]=useState(false);
 const [privLoading,setPrivLoading]=useState(false); const [privMessage,setPrivMessage]=useState('');
 useEffect(()=>{if(token) void getAccountProfileRequest(token).then(p=>{setProfile(p);setAlias(p.display_alias)})},[token]);
 if(credentials) return <CredentialsPanel credentials={credentials}/>; if(!profile||!token)return <p>Memuat profil...</p>;
 const save=async(e:FormEvent)=>{e.preventDefault();try{const p=await updateAccountProfileRequest(token,{alias,avatar_key:profile.avatar_key,preferred_language:profile.preferred_language,timezone:profile.timezone,accessibility_preferences:profile.accessibility_preferences,notification_preferences:profile.notification_preferences});setProfile(p);setMessage('Profil tersimpan.')}catch(err){setMessage(err instanceof Error?err.message:'Gagal')}};
 const passwordAction=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);try{await changePasswordRequest(token,{current_password:data.get('current'),new_password:data.get('next'),password_confirmation:data.get('confirm')});logout();}catch(err){setMessage(err instanceof Error?err.message:'Gagal')}};
 const convert=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);try{setCredentials(await convertAnonymousRequest(token,{alias:d.get('alias'),current_password:d.get('current'),password:d.get('password'),password_confirmation:d.get('confirm'),accept_terms:true,accept_privacy:true,policy_version:'2026-08-05-v1'}))}catch(err){setMessage(err instanceof Error?err.message:'Gagal')}};
 return <div className="mx-auto max-w-3xl space-y-6"><div><h1 className="text-2xl font-bold">Profil dan keamanan akun</h1><p className="mt-1 text-sm text-slate-600">Kelola profil, cara masuk, dan keamanan akun Anda.</p></div>{profile.login_id?<section aria-labelledby="anonymous-login-id" className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-sm font-semibold text-emerald-800">ID Login Anonim</p><div className="mt-2 flex flex-wrap items-center gap-3"><h2 id="anonymous-login-id" className="break-all font-mono text-xl font-bold tracking-wide text-slate-950">{profile.login_id}</h2><Button type="button" size="sm" variant="outline" className="bg-white" onClick={async()=>{await navigator.clipboard.writeText(profile.login_id??'');setLoginIdCopied(true)}}>{loginIdCopied?'Tersalin':'Salin ID'}</Button></div><p className="mt-2 text-sm text-slate-700">Gunakan ID singkat ini saat masuk ke akun anonim. Anda tidak perlu mengingat ID sistem yang panjang.</p></section>:null}{message&&<p role="status" className="rounded bg-slate-100 p-3">{message}</p>}
 <form onSubmit={save} className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-bold">Profil anonim</h2><div><Label htmlFor="palias">Alias</Label><Input id="palias" value={alias} onChange={e=>setAlias(e.target.value)} /></div><div><Label htmlFor="avatar">Avatar sistem</Label><select id="avatar" className="w-full rounded border p-2" value={profile.avatar_key??'avatar-leaf'} onChange={e=>setProfile({...profile,avatar_key:e.target.value})}><option value="avatar-leaf">Daun</option><option value="avatar-sun">Matahari</option><option value="avatar-wave">Gelombang</option><option value="avatar-star">Bintang</option></select></div><div><Label htmlFor="tz">Zona waktu</Label><select id="tz" className="w-full rounded border p-2" value={profile.timezone} onChange={e=>setProfile({...profile,timezone:e.target.value})}><option>Asia/Jayapura</option><option>Asia/Makassar</option><option>Asia/Jakarta</option></select></div><label className="flex gap-2"><input type="checkbox" checked={Boolean(profile.accessibility_preferences?.text_to_speech)} onChange={e=>setProfile({...profile,accessibility_preferences:{...profile.accessibility_preferences,text_to_speech:e.target.checked}})} /> Bacakan teks saat fokus/hover</label><label className="flex gap-2"><input type="checkbox" checked={profile.notification_preferences?.neutral_copy!==false} onChange={e=>setProfile({...profile,notification_preferences:{...profile.notification_preferences,neutral_copy:e.target.checked}})} /> Gunakan teks notifikasi netral</label><Button>Simpan profil</Button></form>
 <form onSubmit={passwordAction} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-bold">Ubah kata sandi</h2><Input name="current" type="password" placeholder="Kata sandi saat ini" required/><Input name="next" type="password" minLength={8} placeholder="Kata sandi baru (minimal 8 karakter)" required/><Input name="confirm" type="password" minLength={8} placeholder="Konfirmasi" required/><Button>Ubah dan keluarkan semua sesi</Button></form>
 {profile.account_mode==='ANONYMOUS'?<section className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-bold">Recovery code</h2><p>Kode hanya akan ditampilkan sekali. Masukkan kata sandi untuk membuat kode baru.</p><Input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Kata sandi"/><Button onClick={async()=>{try{const r=await regenerateRecoveryRequest(token,secret);setMessage(`Recovery code baru (simpan sekarang): ${r.recovery_code}`);setSecret('')}catch(err){setMessage(err instanceof Error?err.message:'Gagal')}}}>Buat recovery code baru</Button></section>:<form onSubmit={convert} className="space-y-3 rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-bold">Ubah akun berbasis email menjadi anonim</h2><p>Email/telepon sebelumnya dipertahankan untuk integritas data, tetapi tidak lagi dapat dipakai login setelah konversi.</p><Input name="alias" placeholder="Alias anonim" required/><Input name="current" type="password" placeholder="Kata sandi saat ini" required/><Input name="password" type="password" minLength={8} placeholder="Kata sandi anonim baru (minimal 8 karakter)" required/><Input name="confirm" type="password" minLength={8} placeholder="Konfirmasi" required/><Button>Konversi akun</Button></form>}
 <form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setPrivLoading(true);try{const d=new FormData(e.currentTarget);const l=d.get('lock_on_bg')==='on';const a=d.get('auto_lock');const r=d.get('require_reauth')==='on';const t=d.get('discreet_titles')==='on';await updatePreferences({lock_on_background:l,auto_lock_minutes:a==='0'||!a?null:Number(a),require_reauth_to_unlock:r,discreet_page_titles:t});setPrivMessage('Pengaturan privasi perangkat berhasil disimpan.')}catch(err){setPrivMessage(err instanceof Error?err.message:'Gagal menyimpan')}finally{setPrivLoading(false)}}} className="space-y-4 rounded-xl border bg-white p-5"><div><h2 className="font-bold text-slate-900">Privasi Perangkat</h2><p className="mt-1 text-xs text-slate-600">Fitur ini membantu mengurangi kemungkinan informasi pribadi terlihat ketika perangkat sedang tidak Anda gunakan.</p></div>{privMessage?<p role="status" className="rounded bg-teal-50 p-2 text-xs font-semibold text-teal-800">{privMessage}</p>:null}<label className="flex items-center gap-3 text-sm text-slate-700 cursor-pointer"><input type="checkbox" name="lock_on_bg" defaultChecked={preferences.lock_on_background} className="h-4 w-4 rounded border-slate-300 text-teal-600 focus:ring-teal-500" /><span>Lindungi layar saat aplikasi berpindah ke latar belakang</span></label><div><Label htmlFor="auto_lock">Kunci otomatis setelah tidak aktif</Label><select id="auto_lock" name="auto_lock" defaultValue={preferences.auto_lock_minutes??0} className="w-full rounded border border-slate-300 p-2 text-sm text-slate-800 focus:border-teal-500 focus:outline-none"><option value="0">Tidak pernah (OFF)</option><option value="1">1 menit</option><option value="5">5 menit</option><option value="15">15 menit</option><option value="30">30 menit</option></select></div><label className="flex items-center gap-3 text-sm text-slate-700 cursor-pointer"><input type="checkbox" name="require_reauth" defaultChecked={preferences.require_reauth_to_unlock} className="h-4 w-4 rounded border-slate-300 text-teal-600 focus:ring-teal-500" /><span>Minta verifikasi ulang untuk membuka layar</span></label><label className="flex items-center gap-3 text-sm text-slate-700 cursor-pointer"><input type="checkbox" name="discreet_titles" defaultChecked={preferences.discreet_page_titles} className="h-4 w-4 rounded border-slate-300 text-teal-600 focus:ring-teal-500" /><span>Gunakan judul tab yang netral</span></label><Button type="submit" disabled={privLoading} className="bg-teal-600 text-white hover:bg-teal-700">{privLoading?'Menyimpan...':'Simpan Privasi Perangkat'}</Button></form>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Sesi</h2><Button variant="outline" onClick={async()=>{await logoutAllRequest(token);logout()}}>Keluar dari semua perangkat</Button></section></div>;
}
