import { FormEvent, useState } from 'react';
import { Link } from 'react-router-dom';
import { recoverAnonymousRequest } from '../api/client';
import { Button } from '../components/ui/button'; import { Input } from '../components/ui/input'; import { Label } from '../components/ui/label';
export function AnonymousRecoveryPage() {
 const [form,setForm]=useState({login_id:'',recovery_code:'',new_password:'',password_confirmation:''}); const [next,setNext]=useState(''); const [error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{setNext((await recoverAnonymousRequest(form)).recovery_code)}catch{setError('Pemulihan tidak dapat diproses. Periksa kredensial dan coba lagi.')}};
 return <main className="mx-auto max-w-xl p-6"><h1 className="text-3xl font-bold">Pulihkan akun anonim</h1>{next?<div className="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-5" role="alert"><h2 className="font-bold">Simpan recovery code baru</h2><p className="mt-3 font-mono text-lg">{next}</p><p>Kode lama dan semua sesi lama sudah tidak berlaku.</p><Link className="underline" to="/login">Ke login</Link></div>:<form onSubmit={submit} className="mt-6 space-y-4"><div><Label htmlFor="rid">ID Login</Label><Input id="rid" value={form.login_id} onChange={e=>setForm({...form,login_id:e.target.value.toUpperCase()})} required /></div><div><Label htmlFor="rcode">Recovery Code</Label><Input id="rcode" value={form.recovery_code} onChange={e=>setForm({...form,recovery_code:e.target.value.toUpperCase()})} required /></div><div><Label htmlFor="rpass">Kata sandi baru</Label><Input id="rpass" type="password" minLength={8} value={form.new_password} onChange={e=>setForm({...form,new_password:e.target.value})} required /><p className="text-xs text-slate-500">Minimal 8 karakter, mengandung huruf dan angka.</p></div><div><Label htmlFor="rconfirm">Konfirmasi</Label><Input id="rconfirm" type="password" minLength={8} value={form.password_confirmation} onChange={e=>setForm({...form,password_confirmation:e.target.value})} required /></div>{error&&<p role="alert" className="text-red-700">{error}</p>}<Button>Reset kata sandi</Button></form>}</main>;
}
