import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest';
import { AppShell } from '../layouts/AppShell';
import { AdminDashboard } from './AdminDashboard';
import { PublicLandingPage } from './public/PublicLandingPage';

const patient={id:'user-1',role:'PASIEN' as const,email:null,full_name:'Alias Aman',account_mode:'ANONYMOUS' as const};
const auth={user:patient as typeof patient|null,token:'token',logout:vi.fn(),handleUnauthorized:vi.fn(),login:vi.fn(),anonymousLogin:vi.fn(),isAuthenticated:true,initializing:false};
vi.mock('../context/AuthContext',()=>({useAuth:()=>auth}));

describe('redesign UI humanis',()=>{
 beforeEach(()=>{auth.user=patient;auth.isAuthenticated=true;vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({items:[]}),{status:200,headers:{'Content-Type':'application/json'}}))});
 afterEach(()=>vi.restoreAllMocks());
 test('landing menempatkan privasi tepat setelah narasi dukungan',()=>{render(<MemoryRouter><PublicLandingPage/></MemoryRouter>);const support=screen.getByRole('heading',{name:'Ruang Aman untuk Bercerita dan Mendapatkan Dukungan',level:1});const privacy=screen.getByRole('heading',{name:'Privasi Anda Adalah Prioritas',level:2});const services=screen.getByRole('heading',{name:'Mulai dari yang Anda butuhkan'});expect(support.compareDocumentPosition(privacy)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(privacy.compareDocumentPosition(services)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByRole('img',{name:/percakapan daring.*pasien bertopeng anonim/i})).toBeInTheDocument();expect(screen.getAllByText('Curhat Ke Konselor').length).toBeGreaterThan(0);expect(screen.getByText('Anonim / tanpa identitas')).toBeInTheDocument();expect(screen.getByText(/GPS tidak diwajibkan/i)).toBeInTheDocument()});
 test('landing menampilkan artikel unggulan dari API dan membuka detailnya',async()=>{vi.mocked(globalThis.fetch).mockImplementation(async input=>new Response(JSON.stringify(String(input).includes('/videos')?{items:[]}:{items:[{title:'Tes HIV dan Masa Jendela',slug:'tes-hiv-dan-masa-jendela',summary:'Ringkasan berbasis sumber resmi.',updated_at:'2026-08-06T00:00:00.000Z'}]}),{status:200,headers:{'Content-Type':'application/json'}}));render(<MemoryRouter><PublicLandingPage/></MemoryRouter>);expect(await screen.findByText('Tes HIV dan Masa Jendela')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Pelajari'})).toHaveAttribute('href','/edukasi/tes-hiv-dan-masa-jendela')});
 test('landing menampilkan carousel video tepat di atas layanan utama',async()=>{vi.mocked(globalThis.fetch).mockImplementation(async input=>new Response(JSON.stringify(String(input).includes('/videos')?{items:[{id:'video-1',title:'Cara Penularan HIV/AIDS',description:'Video edukasi resmi.',source_type:'EXTERNAL',external_url:'https://www.youtube.com/watch?v=mLfb3mMNubc'}]}:{items:[]}),{status:200,headers:{'Content-Type':'application/json'}}));render(<MemoryRouter><PublicLandingPage/></MemoryRouter>);const videoHeading=await screen.findByRole('heading',{name:'Video edukasi pilihan',level:2});const privacyHeading=screen.getByRole('heading',{name:'Privasi Anda Adalah Prioritas',level:2});const servicesHeading=screen.getByRole('heading',{name:'Mulai dari yang Anda butuhkan',level:2});expect(privacyHeading.compareDocumentPosition(videoHeading)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(videoHeading.compareDocumentPosition(servicesHeading)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(screen.getByRole('button',{name:/putar cara penularan hiv\/aids/i})).toBeInTheDocument();expect(document.querySelector('iframe')).toBeNull()});
 test('tombol cepat Curhat Ke Konselor mengambang di atas kontrol halaman dan membuka modal yang sama',async()=>{auth.user=null;auth.isAuthenticated=false;const user=userEvent.setup();render(<MemoryRouter><PublicLandingPage/></MemoryRouter>);const opener=screen.getByRole('button',{name:'Curhat Ke Konselor, tombol cepat'});expect(opener).toHaveClass('fixed');expect(opener).toHaveClass('bottom-[calc(max(1rem,env(safe-area-inset-bottom))+8.5rem)]');opener.focus();await user.click(opener);expect(screen.getByRole('dialog',{name:'Masuk untuk Curhat Ke Konselor'})).toBeInTheDocument();await user.keyboard('{Escape}');expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(opener).toHaveFocus()});
 test('sidebar mobile dapat dibuka dan ditutup tanpa mengubah menu role',async()=>{const user=userEvent.setup();render(<MemoryRouter initialEntries={['/patient']}><Routes><Route element={<AppShell/>}><Route path="/patient" element={<p>Isi dashboard</p>}/></Route></Routes></MemoryRouter>);await user.click(screen.getByRole('button',{name:'Buka menu'}));const closeButtons=screen.getAllByRole('button',{name:'Tutup menu'});expect(closeButtons.length).toBeGreaterThan(0);expect(screen.getAllByText('Konsultasi').length).toBeGreaterThan(0);expect(screen.queryByText('Chat Konselor')).not.toBeInTheDocument();await user.click(closeButtons[closeButtons.length-1]);expect(screen.queryByRole('button',{name:'Tutup menu'})).not.toBeInTheDocument()});
 test('dashboard admin menjelaskan pembatasan dan tidak menampilkan isi chat',()=>{render(<MemoryRouter><AdminDashboard/></MemoryRouter>);expect(screen.getByText(/tidak otomatis memiliki akses/i)).toBeInTheDocument();expect(screen.queryByText(/preview isi chat/i)).not.toBeInTheDocument()});
});
