import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apiFetch } from '../../api/client';
import { useAuth } from '../../context/AuthContext';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { EmptyState, PageHeader, StatusBadge } from '../../components/ui/patterns';

type Message = { public_id:string; kind:'TEXT'|'VOICE_NOTE'; content:string|null; voice_note_public_id:string|null; sender:'YOU'|'COUNSELOR'|'PARTICIPANT'; delivered_at:string|null; read_at:string|null; created_at:string };
type Conversation = { public_id:string; service_type:string; status:string; priority:number; subject:string|null; queued_at:string; messages?:Message[]; service_message?:string; outside_hours?:boolean };
const key = () => crypto.randomUUID().replace(/-/g, '');

function useApi() {
  const { token, handleUnauthorized } = useAuth();
  return useCallback(<T,>(path:string, init:RequestInit={}) => apiFetch<T>(path, init, { token, onUnauthorized:handleUnauthorized }), [token, handleUnauthorized]);
}

export function PatientCounselorListPage() {
  const api=useApi(); const nav=useNavigate();
  const [items,setItems]=useState<Conversation[]>([]); const [error,setError]=useState(''); const [subject,setSubject]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const load=useCallback(()=>api<{items:Conversation[]}>('/counselor-conversations').then(x=>setItems(x.items)).catch(e=>setError(e.message)),[api]);
  useEffect(()=>{void load()},[load]);
  async function create(e:FormEvent){e.preventDefault();if(message.trim().length<1)return;setBusy(true);setError('');try{const c=await api<Conversation>('/counselor-conversations',{method:'POST',body:JSON.stringify({service_type:'COUNSELOR',subject:subject.trim()||undefined,initial_message:message.trim(),priority:0})});nav(`/patient/counselor/${c.public_id}`,{state:{serviceMessage:c.service_message}})}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <div className="space-y-6"><header><p className="text-sm text-slate-500">Layanan privat</p><h1 className="text-2xl font-semibold">Konsultasi</h1><p className="mt-1 text-sm text-slate-600">Bukan layanan darurat atau diagnosis. Maksimal dua sesi aktif.</p></header>
    <Card><CardHeader><CardTitle>Mulai sesi</CardTitle><CardDescription>Ceritakan kebutuhan dukungan Anda tanpa mencantumkan identitas yang tidak perlu.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={create}><label className="block text-sm font-medium">Topik (opsional)<input className="mt-1 w-full rounded-lg border p-2" maxLength={120} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="block text-sm font-medium">Pesan awal<textarea className="mt-1 min-h-28 w-full rounded-lg border p-2" maxLength={2000} required value={message} onChange={e=>setMessage(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<Button disabled={busy}>{busy?'Mengirim…':'Masuk antrean konselor'}</Button></form></CardContent></Card>
    <section aria-labelledby="session-title"><h2 id="session-title" className="mb-3 text-lg font-semibold">Sesi saya</h2><div className="grid gap-3">{items.length===0&&<p className="text-sm text-slate-500">Belum ada sesi.</p>}{items.map(c=><Link className="rounded-xl border bg-white p-4 hover:border-brand" key={c.public_id} to={`/patient/counselor/${c.public_id}`}><div className="flex justify-between gap-2"><span className="font-medium">{c.subject||'Dukungan konselor'}</span><Badge variant="info">{c.status}</Badge></div><p className="mt-1 text-xs text-slate-500">Dibuat {new Date(c.queued_at).toLocaleString('id-ID')}</p></Link>)}</div></section>
  </div>
}

function VoicePlayer({voiceId,resolve}:{voiceId:string;resolve:(id:string)=>Promise<string>}){const[url,setUrl]=useState('');const[error,setError]=useState('');return <div>{url?<audio controls preload="none" className="max-w-full" src={url}>Browser Anda tidak mendukung audio.</audio>:<Button variant="outline" size="sm" onClick={()=>void resolve(voiceId).then(setUrl).catch(e=>setError(e.message))}>Muat voice note</Button>}{error&&<span role="alert" className="ml-2 text-xs">{error}</span>}</div>}
function MessageList({messages,onPlay}:{messages:Message[];onPlay:(id:string)=>Promise<string>}) { return <ol aria-live="polite" aria-label="Daftar pesan" className="space-y-3">{messages.map(m=><li key={m.public_id} className={`max-w-[85%] rounded-xl p-3 ${m.sender==='YOU'?'ml-auto bg-brand text-white':'bg-slate-100 text-slate-900'}`}><p className="text-xs font-semibold">{m.sender==='YOU'?'Anda':m.sender==='COUNSELOR'?'Konselor':'Pengguna'}</p>{m.kind==='VOICE_NOTE'&&m.voice_note_public_id?<VoicePlayer voiceId={m.voice_note_public_id} resolve={onPlay}/>:<p className="whitespace-pre-wrap break-words text-sm">{m.content}</p>}<div className="mt-1 text-right text-[11px] opacity-75"><time>{new Date(m.created_at).toLocaleString('id-ID')}</time>{m.sender==='YOU'&&<span> · {m.read_at?'Dibaca':m.delivered_at?'Terkirim':'Dikirim'}</span>}</div></li>)}</ol> }

export function CounselorConversationPage({staff=false,canClose=true}:{staff?:boolean;canClose?:boolean}) {
  const {id=''}=useParams(); const api=useApi(); const [conversation,setConversation]=useState<Conversation|null>(null); const [text,setText]=useState(''); const [error,setError]=useState(''); const [network,setNetwork]=useState<'online'|'retrying'>('online'); const [upload,setUpload]=useState(0); const attempts=useRef(0);
  const detailPath=`/counselor-conversations/${encodeURIComponent(id)}`;
  const load=useCallback(async()=>{try{const c=await api<Conversation>(detailPath);setConversation(c);setNetwork('online');attempts.current=0;void api(`${detailPath}/read`,{method:'POST'})}catch(e){attempts.current++;setNetwork('retrying');setError((e as Error).message)}},[api,detailPath]);
  useEffect(()=>{void load();let timer:number;const schedule=()=>{const delay=document.hidden?30000:Math.min(15000,3000*2**attempts.current);timer=window.setTimeout(async()=>{await load();schedule()},delay)};schedule();const visible=()=>{if(!document.hidden)void load()};document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(timer);document.removeEventListener('visibilitychange',visible)}},[load]);
  async function send(e:FormEvent){e.preventDefault();const content=text.trim();if(!content)return;setText('');try{await api(staff?`/counselor/conversations/${encodeURIComponent(id)}/reply`:`${detailPath}/messages`,{method:'POST',body:JSON.stringify({content,idempotency_key:key()})});await load()}catch(err){setText(content);setError((err as Error).message)}}
  async function play(publicId:string){const x=await api<{download_url:string}>(`/counselor-voice-notes/${encodeURIComponent(publicId)}`);return x.download_url}
  async function voice(file:File){if(file.size>5*1024*1024){setError('Voice note terlalu besar.');return}try{setUpload(10);const meta={content_type:file.type,file_size_bytes:file.size,duration_seconds:1};const session=await api<{upload_session_id:string;upload_url:string}>(`${detailPath}/voice-notes/upload-url`,{method:'POST',body:JSON.stringify(meta)});setUpload(40);const put=await fetch(session.upload_url,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!put.ok)throw new Error('Upload voice note gagal');setUpload(80);await api(`${detailPath}/voice-notes/commit`,{method:'POST',body:JSON.stringify({...meta,upload_session_id:session.upload_session_id,idempotency_key:key()})});setUpload(100);await load();window.setTimeout(()=>setUpload(0),800)}catch(e){setUpload(0);setError((e as Error).message)}}
  async function action(name:'close'|'block'|'request-reassignment'|'escalate'){if(['close','block','request-reassignment'].includes(name)&&!window.confirm('Konfirmasi tindakan ini?'))return;try{const body=name==='escalate'?{reason:'Memerlukan peninjauan supervisor'}:{};await api(staff?`/counselor/conversations/${id}/${name}`:`${detailPath}/${name}`,{method:'POST',body:JSON.stringify(body)});await load()}catch(e){setError((e as Error).message)}}
  async function report(){try{await api(`${detailPath}/report`,{method:'POST',body:JSON.stringify({reason:'OTHER',description:'Dilaporkan dari halaman percakapan'})});setError('Laporan berhasil dikirim.')}catch(e){setError((e as Error).message)}}
  if(!conversation)return <p role="status">Memuat percakapan… {error}</p>;
  return <div className="mx-auto max-w-3xl space-y-4"><header className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-xl font-semibold">{conversation.subject||'Percakapan dukungan'}</h1><p className="text-sm text-slate-500">Status {conversation.status}</p></div><span role="status" className={`text-sm ${network==='online'?'text-green-700':'text-amber-700'}`}>{network==='online'?'Terhubung':'Mencoba menyambung kembali…'}</span></header>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error} <button className="underline" onClick={()=>void load()}>Coba lagi</button></p>}
    <Card><CardContent className="max-h-[55vh] overflow-y-auto pt-5"><MessageList messages={conversation.messages||[]} onPlay={play}/></CardContent></Card>
    {!['CLOSED','CANCELLED'].includes(conversation.status)&&<form onSubmit={send} className="space-y-2"><label className="sr-only" htmlFor="chat-message">Pesan</label><textarea id="chat-message" maxLength={2000} className="min-h-24 w-full rounded-lg border p-3" value={text} onChange={e=>setText(e.target.value)} placeholder="Tulis pesan…"/><div className="flex flex-wrap gap-2"><Button>Kirim pesan</Button><label className="cursor-pointer rounded-lg border px-3 py-2 text-sm font-medium">Kirim voice note<input className="sr-only" type="file" accept="audio/webm,audio/ogg,audio/mpeg,audio/mp4" onChange={e=>e.target.files?.[0]&&void voice(e.target.files[0])}/></label></div>{upload>0&&<progress aria-label="Progres upload voice note" className="w-full" max={100} value={upload}/>}</form>}
    <div className="flex flex-wrap gap-2">{staff?<><Button variant="outline" onClick={()=>void action('escalate')}>Eskalasi</Button>{canClose?<Button variant="outline" onClick={()=>void action('close')}>Tutup sesi</Button>:null}</>:<><Button variant="outline" onClick={()=>void report()}>Laporkan sesi</Button><Button variant="outline" onClick={()=>void action('request-reassignment')}>Minta konselor lain</Button><Button variant="outline" onClick={()=>void action('block')}>Blokir konselor & tetap antre</Button><Button variant="outline" onClick={()=>void action('close')}>Tutup sesi</Button></>}</div>
  </div>
}

export function CounselorQueuePage(){const api=useApi();const nav=useNavigate();const[items,setItems]=useState<Conversation[]>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const load=useCallback(()=>{setLoading(true);setError('');return api<{items:Conversation[]}>('/counselor/queue').then(x=>setItems(x.items)).catch(()=>setError('Antrean belum dapat dimuat.')).finally(()=>setLoading(false))},[api]);useEffect(()=>{void load()},[load]);async function claim(id:string){try{await api(`/counselor/conversations/${id}/assign`,{method:'POST',body:'{}'});nav(`/counselor/conversations/${id}`)}catch(e){setError((e as Error).message);void load()}}return <div className="page-shell"><PageHeader eyebrow="Ruang kerja konselor" title="Antrean konsultasi" description="Ambil sesi sesuai kapasitas Anda. Identitas dan isi percakapan baru tersedia setelah penugasan yang sah." action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}>Perbarui</Button><StatusBadge variant="success">Profil terverifikasi</StatusBadge></div>}/><section aria-labelledby="counselor-summary"><h2 id="counselor-summary" className="sr-only">Ringkasan antrean</h2><div className="grid gap-4 sm:grid-cols-3"><Card><CardContent><p className="text-sm text-slate-500">Dapat diambil</p><p className="mt-1 text-2xl font-bold">{loading?'—':items.length}</p></CardContent></Card><Card><CardContent><p className="text-sm text-slate-500">Status layanan</p><p className="mt-1 font-bold text-emerald-800">Izin aktif</p></CardContent></Card><Card><CardContent><p className="text-sm text-slate-500">Privasi antrean</p><p className="mt-1 font-bold">Metadata saja</p></CardContent></Card></div></section>{error?<p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{error}</p>:null}<section aria-labelledby="queue-title"><h2 id="queue-title" className="text-2xl font-bold">Sesi yang tersedia</h2><div className="mt-5 grid gap-3">{!loading&&!error&&items.length===0?<EmptyState icon="chat" title="Antrean sedang kosong" description="Sesi yang memenuhi penugasan Anda akan muncul di sini."/>:items.map(c=><Card key={c.public_id}><CardContent className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-bold">Sesi menunggu penugasan</p><p className="mt-1 text-sm text-slate-500">Masuk antrean {new Date(c.queued_at).toLocaleString('id-ID')} · Prioritas {c.priority}</p></div><Button onClick={()=>void claim(c.public_id)}>Ambil sesi</Button></CardContent></Card>)}</div></section></div>}
