import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { vi } from 'vitest';
import { ComplaintTrackingPage, PublicComplaintPage } from './ComplaintPages';
import { CounselorConversationPage } from './CounselorPages';

const { unauthorized }=vi.hoisted(()=>({unauthorized:vi.fn()}));
vi.mock('../../context/AuthContext',()=>({useAuth:()=>({token:'test-token',handleUnauthorized:unauthorized})}));
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});

test('anonymous complaint requires consent without contact identity and shows tracking secret once',async()=>{const secret='TRK-ABCDE-FGHJK-LMNPQ';vi.spyOn(globalThis,'fetch').mockResolvedValue(response({public_id:'tkt_test',tracking_code:'TC-ABCD-EFGH-IJKL',tracking_secret:secret,subject:'Uji',status:'SUBMITTED'},201));const user=userEvent.setup();render(<MemoryRouter><PublicComplaintPage/></MemoryRouter>);expect(screen.queryByLabelText(/email|telepon|phone|gps/i)).not.toBeInTheDocument();await user.selectOptions(screen.getByLabelText('Kategori'),'PRIVACY');await user.type(screen.getByLabelText('Subjek'),'Privasi DATA UJI');await user.type(screen.getByLabelText('Keterangan'),'Keterangan pengaduan sintetis');const checks=screen.getAllByRole('checkbox');await user.click(checks[checks.length-1]);await user.click(screen.getByRole('button',{name:'Kirim pengaduan'}));expect(await screen.findByText(secret)).toBeInTheDocument();const payload=JSON.parse(String((globalThis.fetch as any).mock.calls[0][1].body));expect(payload.privacy_level).toBe('ANONYMOUS');expect(payload).not.toHaveProperty('email');expect(JSON.stringify(localStorage)+JSON.stringify(sessionStorage)).not.toContain(secret)});

test('tracking secret uses password input and private request header',async()=>{const fetchMock=vi.spyOn(globalThis,'fetch').mockResolvedValue(response({public_id:'tkt_test',tracking_code:'TC-ABCD-EFGH-IJKL',subject:'Uji',description:'Aman',status:'SUBMITTED',sla_status:'ON_TRACK',target_response_local:'2026-08-05 Asia/Jayapura',target_resolution_local:'2026-08-06 Asia/Jayapura'}));const user=userEvent.setup();render(<MemoryRouter><ComplaintTrackingPage/></MemoryRouter>);const secret=screen.getByLabelText('Rahasia pelacakan');expect(secret).toHaveAttribute('type','password');await user.type(screen.getByLabelText('Nomor tiket'),'TC-ABCD-EFGH-IJKL');await user.type(secret,'TRK-ABCDE-FGHJK-LMNPQ');await user.click(screen.getByRole('button',{name:'Lacak'}));expect(await screen.findByText('Uji')).toBeInTheDocument();expect(new Headers(fetchMock.mock.calls[0][1]?.headers).get('X-Tracking-Secret')).toBe('TRK-ABCDE-FGHJK-LMNPQ')});

test('voice note exposes keyboard-native play and pause controls after authorized URL resolution',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.includes('/counselor-voice-notes/'))return response({download_url:'https://storage.invalid/private-signed'});if(init?.method==='POST')return response({read_count:1});return response({public_id:'svc_test',subject:'Dukungan',status:'ACTIVE',messages:[{public_id:'msg_test',kind:'VOICE_NOTE',content:null,voice_note_public_id:'vcn_test',sender:'COUNSELOR',delivered_at:null,read_at:null,created_at:'2026-08-05T00:00:00.000Z'}]})});const user=userEvent.setup();const view=render(<MemoryRouter initialEntries={['/patient/counselor/svc_test']}><Routes><Route path="/patient/counselor/:id" element={<CounselorConversationPage/>}/></Routes></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Muat voice note'}));await screen.findByText('Browser Anda tidak mendukung audio.');const audio=view.container.querySelector('audio');expect(audio).toHaveAttribute('controls');expect(audio).toHaveAttribute('src','https://storage.invalid/private-signed')});
