import { FastifyInstance } from 'fastify'; import { prisma } from '../../db/prisma'; import { env } from '../../config/env'; import { generateDownloadUrl } from '../voiceNotes/storage.service'; import { pagination } from './content.validators';
const cache = {
  'Cache-Control': 'public, max-age=60, stale-while-revalidate=300',
  'X-SEHATICARE-OFFLINE-SAFE': '1'
};
export default async function publicContentRoutes(app:FastifyInstance){
 app.get('/regions',async(req,reply)=>{reply.headers(cache);const q=(req.query as {q?:string}).q?.trim().slice(0,80);return{items:await prisma.regions.findMany({where:{is_active:true,...(q?{name:{contains:q,mode:'insensitive'}}:{})},orderBy:[{type:'asc'},{name:'asc'}],take:100,select:{id:true,code:true,name:true,type:true,parent_id:true}})}});
 app.get('/content-categories',async(req,reply)=>{reply.headers(cache);return{items:await prisma.content_categories.findMany({where:{is_active:true},orderBy:{name:'asc'},select:{slug:true,name:true}})}});
 app.get('/statistics',async(req,reply)=>{const p=pagination(req.query);reply.headers(cache);const where={publication_status:'PUBLISHED' as const,...(p.regionId?{region_id:p.regionId}:{}),...(p.year?{year:p.year}:{}),...(p.periodType?{period_type:p.periodType}:{})};const [rows,total]=await Promise.all([prisma.case_statistics.findMany({where,skip:p.skip,take:p.limit,orderBy:{period_end:'desc'},include:{regions:{select:{code:true,name:true}}}}),prisma.case_statistics.count({where})]);return{page:p.page,limit:p.limit,total,items:rows.map(r=>({id:r.id,region:r.regions,period_start:r.period_start,period_end:r.period_end,year:r.year,period_type:r.period_type,data_category:r.data_category,count_suppressed:r.case_count<env.STATISTICS_MINIMUM_PUBLIC_COUNT,case_count:r.case_count<env.STATISTICS_MINIMUM_PUBLIC_COUNT?null:r.case_count,source:r.source_name,source_publication:r.source_publication,source_url:r.source_url,updated_on:r.updated_on,methodology_note:r.methodology_note,is_sample:r.is_sample}))}});
 app.get('/articles',async(req,reply)=>{const p=pagination(req.query);reply.headers(cache);const where={publication_status:'PUBLISHED' as const,...(p.q?{OR:[{title:{contains:p.q,mode:'insensitive' as const}},{summary:{contains:p.q,mode:'insensitive' as const}}]}:{}),...(p.category?{content_categories:{slug:p.category}}:{})};const [items,total]=await Promise.all([prisma.education_articles.findMany({where,skip:p.skip,take:p.limit,orderBy:[{featured:'desc'},{published_at:'desc'}],select:{title:true,slug:true,summary:true,thumbnail_key:true,thumbnail_alt:true,language:true,source_reference:true,reading_minutes:true,featured:true,published_at:true,updated_at:true,content_categories:{select:{slug:true,name:true}}}}),prisma.education_articles.count({where})]);return{page:p.page,limit:p.limit,total,items}});
 app.get('/articles/:slug',async(req,reply)=>{reply.headers(cache);const a=await prisma.education_articles.findFirst({where:{slug:(req.params as any).slug,publication_status:'PUBLISHED'},select:{title:true,slug:true,summary:true,body_markdown:true,thumbnail_key:true,thumbnail_alt:true,language:true,source_reference:true,reading_minutes:true,published_at:true,updated_at:true,content_categories:{select:{slug:true,name:true}}}});return a??reply.code(404).send({message:'Article not found'})});
 app.get('/videos',async(req,reply)=>{const p=pagination(req.query);reply.headers(cache);const where={publication_status:'PUBLISHED' as const};const [items,total]=await Promise.all([prisma.education_videos.findMany({where,skip:p.skip,take:p.limit,orderBy:{published_at:'desc'},select:{id:true,title:true,description:true,source_type:true,external_url:true,thumbnail_key:true,thumbnail_alt:true,duration_seconds:true,file_size_bytes:true,language:true,published_at:true}}),prisma.education_videos.count({where})]);return{page:p.page,limit:p.limit,total,items}});
 app.get('/videos/:id',async(req,reply)=>{reply.headers(cache);const v=await prisma.education_videos.findFirst({where:{id:(req.params as any).id,publication_status:'PUBLISHED'},select:{id:true,title:true,description:true,source_type:true,external_url:true,thumbnail_key:true,thumbnail_alt:true,duration_seconds:true,file_size_bytes:true,language:true,subtitle_text:true,transcript_text:true,published_at:true}});return v??reply.code(404).send({message:'Video not found'})});
 app.get('/videos/:id/playback',async(req,reply)=>{reply.header('Cache-Control','private, no-store');const v=await prisma.education_videos.findFirst({where:{id:(req.params as any).id,publication_status:'PUBLISHED',source_type:'UPLOAD'},select:{storage_key:true}});if(!v?.storage_key)return reply.code(404).send({message:'Video playback not found'});return{playback_url:await generateDownloadUrl(v.storage_key)}});
 app.get('/facilities',async(req,reply)=>{const p=pagination(req.query);reply.headers(cache);const where={is_active:true,verification_status:'VERIFIED' as const,...(p.regionId?{region_id:p.regionId}:{}),...(p.type?{facility_type:p.type}:{}),...(p.q?{name:{contains:p.q,mode:'insensitive' as const}}:{}),...(p.service?{facility_services:{some:{service:p.service,verified:true}}}:{})};const [items,total]=await Promise.all([prisma.health_facilities.findMany({where,skip:p.skip,take:p.limit,orderBy:{name:'asc'},select:{id:true,name:true,facility_type:true,district_name:true,address:true,public_contact:true,service_hours:true,description:true,verified_at:true,updated_at:true,is_sample:true,source_name:true,regions:{select:{code:true,name:true}},facility_services:{where:{verified:true},select:{service:true}}}}),prisma.health_facilities.count({where})]);return{page:p.page,limit:p.limit,total,items}});
 app.get('/facilities/:id',async(req,reply)=>{reply.headers(cache);const f=await prisma.health_facilities.findFirst({where:{id:(req.params as any).id,is_active:true,verification_status:'VERIFIED'},select:{id:true,name:true,facility_type:true,district_name:true,address:true,public_contact:true,service_hours:true,description:true,verified_at:true,updated_at:true,is_sample:true,source_name:true,regions:{select:{code:true,name:true}},facility_services:{where:{verified:true},select:{service:true}}}});return f??reply.code(404).send({message:'Facility not found'})});
 app.get('/portal',async(req,reply)=>{reply.headers(cache);const rows=await prisma.portal_contents.findMany({where:{publication_status:'PUBLISHED'},orderBy:[{display_order:'asc'},{created_at:'asc'}],select:{id:true,section:true,title:true,summary:true,link_url:true,media_url:true,article_id:true,video_id:true,display_order:true,updated_at:true,article:{select:{id:true,slug:true,title:true,summary:true}},video:{select:{id:true,title:true,description:true,source_type:true,external_url:true,thumbnail_key:true,thumbnail_alt:true}}}});const grouped:Record<string,typeof rows>={hero:[],carouselImages:[],edukasiAwal:[],video:[],infografis:[],faq:[],banner:[]};for(const item of rows){if(!grouped[item.section])grouped[item.section]=[];grouped[item.section].push(item)}return{items:rows,grouped}});
}
