import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiFetch } from '../../api/client';
import { useAuth } from '../../context/AuthContext';
import { Button } from '../../components/ui/button';
import { Card, CardContent } from '../../components/ui/card';
import { StatusBadge } from '../../components/ui/patterns';

type Message={id:string;kind:string;content:string|null;sender:'YOU'|'COUNSELOR';voice_note_id:string|null;created_at:string;delivered_at:string|null;read_at:string|null};
type Detail={id:string;title:string;status:string;created_at:string;updated_at:string;capabilities:{reply:boolean;voice:boolean;close:boolean;report:boolean;reassign:boolean};messages:Message[]};

export function UnifiedConsultationDetailPage(){
 const{id=''}=useParams();const{token,handleUnauthorized}=useAuth();const[item,setItem]=useState<Detail|null>(null);const[error,setError]=useState('');const[text,setText]=useState('');
 const api=useCallback(<T,>(path:string,init:RequestInit={})=>apiFetch<T>(path,init,{token,onUnauthorized:handleUnauthorized}),[token,handleUnauthorized]);
 const load=useCallback(()=>api<Detail>(`/consultations-unified/${encodeURIComponent(id)}`).then(setItem).catch(e=>setError(e.message)),[api,id]);
 useEffect(()=>{void load()},[load]);
 async function play(voiceId:string){try{const result=await api<{download_url:string}>(`/consultations-unified/${encodeURIComponent(id)}/voice-notes/${encodeURIComponent(voiceId)}`);window.location.assign(result.download_url)}catch(e){setError((e as Error).message)}}
 async function send(event:FormEvent){event.preventDefault();if(!text.trim())return;try{await api(`/counselor-conversations/${encodeURIComponent(id)}/messages`,{method:'POST',body:JSON.stringify({content:text.trim(),idempotency_key:crypto.randomUUID().replace(/-/g,'')})});setText('');await load()}catch(e){setError((e as Error).message)}}
 async function action(name:'close'|'report'|'request-reassignment'){if(!window.confirm('Lanjutkan tindakan ini?'))return;try{const body=name==='report'?{reason:'OTHER',description:'Dilaporkan dari halaman konsultasi terpadu'}:{};await api(`/counselor-conversations/${encodeURIComponent(id)}/${name}`,{method:'POST',body:JSON.stringify(body)});await load()}catch(e){setError((e as Error).message)}}
 if(!item)return <p role="status">Memuat konsultasi… {error}</p>;
 return <div className="mx-auto max-w-3xl space-y-4"><Link className="text-sm font-semibold text-brand underline" to="/patient/consultations">← Kembali ke konsultasi</Link><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-slate-500">Riwayat dan percakapan</p><h1 className="text-2xl font-bold">{item.title}</h1></div><StatusBadge variant={item.status==='CLOSED'?'neutral':'success'}>{item.status}</StatusBadge></header>{error?<p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>:null}<Card><CardContent><ol aria-label="Pesan konsultasi" className="space-y-3">{item.messages.length===0?<li className="text-sm text-slate-500">Belum ada pesan.</li>:item.messages.map(message=><li key={message.id} className={`max-w-[88%] rounded-xl p-3 ${message.sender==='YOU'?'ml-auto bg-brand text-white':'bg-slate-100'}`}><strong className="text-xs">{message.sender==='YOU'?'Anda':'Konselor'}</strong>{message.kind==='VOICE_NOTE'&&message.voice_note_id?<Button className="mt-2 block" size="sm" variant="outline" onClick={()=>void play(message.voice_note_id!)}>Putar voice note</Button>:<p className="whitespace-pre-wrap break-words text-sm">{message.content||'[Pesan tidak tersedia]'}</p>}<time className="mt-1 block text-right text-[11px] opacity-75">{new Date(message.created_at).toLocaleString('id-ID')}</time></li>)}</ol></CardContent></Card>{!item.capabilities.reply?<p className="rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm text-sky-900">Riwayat ini tetap dapat dibaca. Untuk percakapan baru, gunakan tombol “Curhat Ke Konselor”.</p>:<><form onSubmit={send} className="space-y-2"><label className="block text-sm font-semibold">Balasan<textarea className="mt-1 min-h-24 w-full rounded-xl border p-3" maxLength={2000} required value={text} onChange={event=>setText(event.target.value)}/></label><Button>Kirim pesan</Button></form><div className="flex flex-wrap gap-2">{item.capabilities.report?<Button variant="outline" onClick={()=>void action('report')}>Laporkan</Button>:null}{item.capabilities.reassign?<Button variant="outline" onClick={()=>void action('request-reassignment')}>Minta konselor lain</Button>:null}{item.capabilities.close?<Button variant="outline" onClick={()=>void action('close')}>Tutup sesi</Button>:null}</div></>}</div>
}
