import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, vi } from 'vitest';
import { UnifiedConsultationsPage } from './UnifiedConsultationsPage';

const {unauthorized}=vi.hoisted(()=>({unauthorized:vi.fn()}));
vi.mock('../../context/AuthContext',()=>({useAuth:()=>({token:'test-token',handleUnauthorized:unauthorized})}));
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const candidate={public_id:'usr_1234567890abcdef1234567890abcdef',professional_name:'Dr. Aman',profession:'Dokter',facility:{id:'facility-1',name:'Puskesmas DATA UJI'},region:{id:'region-1',name:'Ternate'},competencies:['EMOTIONAL_SUPPORT'],languages:['Bahasa Indonesia'],available_now:true,estimated_response:'Antrean paling singkat',reasons:['Sesuai topik kebutuhan','Tersedia saat ini'],recommendation_scope:'FACILITY'};

function mockApi(withCandidate=true){return vi.spyOn(globalThis,'fetch').mockImplementation(async input=>{const url=String(input);if(url.includes('/consultation-overview'))return response({items:[]});if(url.includes('/public/regions'))return response({items:[{id:'30000000-0000-4000-8000-000000000001',name:'Kota Ternate',type:'CITY_REGENCY'}]});if(url.includes('/public/facilities'))return response({items:[{id:'20000000-0000-4000-8000-000000000001',name:'Puskesmas DATA UJI',regions:{name:'Kota Ternate'}}]});if(url.includes('/consultation-counselors/recommendations'))return response({recommended:withCandidate?candidate:null,items:withCandidate?[candidate]:[],fallback:'Aman'});if(url.includes('/counselor-conversations'))return response({public_id:'svc_1234567890abcdef1234567890abcdef',status:'ASSIGNED'},201);return response({message:'Not found'},404)})}

afterEach(()=>vi.restoreAllMocks());
test('single consultation page has Curhat Ke Konselor, integrated tabs, empty state, and no GPS requirement',async()=>{mockApi();const user=userEvent.setup();render(<MemoryRouter><UnifiedConsultationsPage/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Konsultasi'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Aktif (0)'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Riwayat (0)'})).toBeInTheDocument();const open=screen.getByRole('button',{name:'Curhat Ke Konselor'});await user.click(open);expect(screen.getByRole('dialog',{name:'Curhat Ke Konselor'})).toBeInTheDocument();expect(screen.getByLabelText('Ceritakan kebutuhan Anda')).toBeInTheDocument();expect(screen.getByLabelText('Topik opsional')).toBeInTheDocument();expect(screen.getByLabelText('Kabupaten/kota (opsional)')).toBeInTheDocument();expect(screen.queryByLabelText(/GPS|koordinat/i)).not.toBeInTheDocument()});
test('recommendation step presents recommended, alternative, and fastest choices',async()=>{mockApi();const user=userEvent.setup();render(<MemoryRouter><UnifiedConsultationsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Curhat Ke Konselor'}));fireEvent.change(screen.getByLabelText('Ceritakan kebutuhan Anda'),{target:{value:'Saya membutuhkan dukungan emosional tanpa identitas pribadi.'}});await user.selectOptions(screen.getByLabelText('Topik opsional'),'EMOTIONAL_SUPPORT');await user.click(screen.getByRole('button',{name:'Lihat pilihan konselor'}));expect(await screen.findByText('Dr. Aman')).toBeInTheDocument();expect(screen.getByText('Gunakan konselor yang direkomendasikan')).toBeInTheDocument();expect(screen.getByText('Pilih konselor lain')).toBeInTheDocument();expect(screen.getByText('Hubungkan dengan konselor paling cepat tersedia')).toBeInTheDocument()});
test('modal closes with Escape and returns focus to opening button',async()=>{mockApi();const user=userEvent.setup();render(<MemoryRouter><UnifiedConsultationsPage/></MemoryRouter>);const open=await screen.findByRole('button',{name:'Curhat Ke Konselor'});await user.click(open);await user.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(open).toHaveFocus()});
test('when nobody is eligible the honest general queue option remains available',async()=>{mockApi(false);const user=userEvent.setup();render(<MemoryRouter><UnifiedConsultationsPage/></MemoryRouter>);await user.click(await screen.findByRole('button',{name:'Curhat Ke Konselor'}));fireEvent.change(screen.getByLabelText('Ceritakan kebutuhan Anda'),{target:{value:'Saya membutuhkan informasi layanan yang aman.'}});await user.click(screen.getByRole('button',{name:'Lihat pilihan konselor'}));expect(await screen.findByText('Masuk antrean umum')).toBeInTheDocument();expect(screen.getByText(/tanpa janji waktu tertentu/i)).toBeInTheDocument()});
