import { z } from 'zod'; import { isValidTimeZone } from './timezone';
const safe=(max:number)=>z.string().trim().min(1).max(max).refine(v=>!/[<>]/.test(v),'Markup is not allowed');const tz=z.string().trim().refine(isValidTimeZone,'Invalid IANA timezone');const time=z.string().regex(/^(?:[01][0-9]|2[0-3]):[0-5][0-9]$/);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(`${v}T00:00:00Z`)),'Invalid date');
export const listSchema=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(20),status:z.string().max(30).optional(),from:z.coerce.date().optional(),to:z.coerce.date().optional()});
const scheduleBase=z.object({user_public_id:z.string().regex(/^usr_[a-f0-9]{32}$/).optional(),facility_id:z.string().uuid().optional(),starts_at:z.string().datetime(),timezone:tz,control_type:safe(80),user_note:safe(1000).optional(),worker_note_private:safe(1000).optional(),worker_note_shared:safe(1000).optional(),reminder_enabled:z.boolean().default(false),reminder_minutes:z.number().int().min(5).max(10080).optional()});
export const scheduleSchema=scheduleBase.refine(v=>!v.reminder_enabled||Boolean(v.reminder_minutes),{message:'Reminder time required'});
export const schedulePatchSchema:z.ZodType<any>=scheduleBase.omit({user_public_id:true}).partial().refine(v=>Object.keys(v).length>0,'No changes').refine(v=>!v.starts_at||new Date(v.starts_at).getTime()>=Date.now()-300_000,'Invalid date');
const reminderBase=z.object({display_label:safe(80),medication_name:safe(120).optional(),reveal_name_in_app:z.boolean().default(false),dosage_text:safe(120).optional(),instructions:safe(500).optional(),timezone:tz,recurrence:z.enum(['ONCE','DAILY','WEEKLY','MULTIPLE_DAILY']),start_date:date,end_date:date.optional(),active_days:z.array(z.number().int().min(0).max(6)).max(7).default([]),times:z.array(time).min(1).max(6),notification_privacy:z.enum(['NEUTRAL','LABEL_IN_APP']).default('NEUTRAL')});
export const reminderSchema=reminderBase.refine(v=>!v.end_date||v.end_date>=v.start_date,{message:'End date precedes start date'}).refine(v=>v.recurrence!=='WEEKLY'||v.active_days.length>0,{message:'Active days required'}).refine(v=>new Set(v.times).size===v.times.length,{message:'Duplicate time'}).refine(v=>v.recurrence==='MULTIPLE_DAILY'||v.times.length===1,{message:'Use MULTIPLE_DAILY for multiple times'});
export const reminderPatchSchema=reminderBase.partial().refine(v=>Object.keys(v).length>0,'No changes');
export const occurrenceNote=z.object({note:safe(300).optional()});export const snoozeSchema=occurrenceNote.extend({minutes:z.union([z.literal(5),z.literal(10),z.literal(30)])});
export const preferenceSchema=z.object({control_schedule_enabled:z.boolean(),medication_enabled:z.boolean(),in_app_enabled:z.boolean(),browser_enabled:z.boolean(),sound_enabled:z.boolean(),vibration_enabled:z.boolean(),preview_detail:z.boolean(),hide_medication_name:z.boolean(),quiet_hours_start:time.nullable(),quiet_hours_end:time.nullable(),timezone:tz}).partial().refine(v=>(v.quiet_hours_start===undefined&&v.quiet_hours_end===undefined)||(v.quiet_hours_start!==undefined&&v.quiet_hours_end!==undefined),{message:'Both quiet hours values are required'});
export function page(v:unknown){const p=listSchema.parse(v);return{...p,skip:(p.page-1)*p.limit}}
