import { randomUUID } from 'node:crypto'; import { prisma } from '../../db/prisma'; import { addLocalDays,inQuietHours,localDateKey,localDateTimeToUtc,localTimeKey,weekday } from './timezone'; import { evaluateOverdueControlSchedules } from '../care/careSignals.service';
export const NEUTRAL_MEDICATION='Saatnya memeriksa pengingat Anda.';export const NEUTRAL_CONTROL='Anda memiliki jadwal yang akan datang.';export const NEUTRAL_UPDATE='Ada pembaruan pada jadwal Anda.';const LOCK_ID=8374301;const WINDOW_DAYS=2;const CATCH_UP_MS=15*60_000;
export function neutralTextIsSafe(text:string){return[NEUTRAL_MEDICATION,NEUTRAL_CONTROL,NEUTRAL_UPDATE].includes(text)&&!/\b(?:HIV|AIDS|ODHIV|ARV)\b/i.test(text)}
function applies(r:any,dateKey:string){const start=r.start_date.toISOString().slice(0,10);const end=r.end_date?.toISOString().slice(0,10);if(dateKey<start||(end&&dateKey>end))return false;if(r.recurrence==='ONCE')return dateKey===start;if(r.recurrence==='WEEKLY')return r.active_days.includes(weekday(dateKey));return true}
async function createPendingDelivery(userId:string,key:string,kind:'CONTROL_SCHEDULE'|'MEDICATION_REMINDER'|'SCHEDULE_UPDATED',resource:string,text:string,dueAt:Date){if(!neutralTextIsSafe(text))throw new Error('Unsafe notification copy');await prisma.notification_deliveries.upsert({where:{deduplication_key:key},update:{},create:{id:randomUUID(),user_id:userId,deduplication_key:key,kind,resource_public_id:resource,neutral_text:text,due_at:dueAt,updated_at:new Date()}})}
async function generateOccurrences(now:Date){const reminders=await prisma.medication_reminders.findMany({where:{is_active:true,deleted_at:null},include:{times:true}});for(const r of reminders){const today=localDateKey(now,r.timezone);for(let offset=0;offset<=WINDOW_DAYS;offset++){const dateKey=addLocalDays(today,offset);if(!applies(r,dateKey))continue;for(const t of r.times){const scheduled=localDateTimeToUtc(dateKey,t.local_time,r.timezone);const occurrence=await prisma.medication_occurrences.upsert({where:{reminder_id_scheduled_at:{reminder_id:r.id,scheduled_at:scheduled}},update:{},create:{id:randomUUID(),reminder_id:r.id,user_id:r.user_id,scheduled_at:scheduled,updated_at:now}});await createPendingDelivery(r.user_id,`med:${occurrence.public_id}:initial`,'MEDICATION_REMINDER',occurrence.public_id,NEUTRAL_MEDICATION,scheduled)}}}}
async function generateControlDeliveries(now:Date){const max=new Date(now.getTime()+(WINDOW_DAYS+1)*86400_000);const schedules=await prisma.control_schedules.findMany({where:{reminder_enabled:true,status:{in:['SCHEDULED','CONFIRMED']},starts_at:{lte:max,gte:new Date(now.getTime()-CATCH_UP_MS)}}});for(const s of schedules){const due=new Date(s.starts_at.getTime()-(s.reminder_minutes??1440)*60_000);await createPendingDelivery(s.user_id,`control:${s.public_id}:${s.reminder_minutes}`,'CONTROL_SCHEDULE',s.public_id,NEUTRAL_CONTROL,due)}}
async function resourceAllowed(d:any){const pref=await prisma.notification_preferences.findUnique({where:{user_id:d.user_id}});if(pref&&!pref.in_app_enabled)return{allowed:false,pref};if(d.kind==='CONTROL_SCHEDULE'){const s=await prisma.control_schedules.findUnique({where:{public_id:d.resource_public_id}});return{allowed:Boolean(s&&s.reminder_enabled&&['SCHEDULED','CONFIRMED'].includes(s.status)&&(pref?.control_schedule_enabled??true)),pref}}if(d.kind==='MEDICATION_REMINDER'){const o=await prisma.medication_occurrences.findUnique({where:{public_id:d.resource_public_id},include:{reminder:true}});return{allowed:Boolean(o&&o.reminder.is_active&&!o.reminder.deleted_at&&['PENDING','SNOOZED'].includes(o.status)&&(pref?.medication_enabled??true)),pref}}return{allowed:true,pref}}
async function deliver(now:Date,simulateFailure=false){const pending=await prisma.notification_deliveries.findMany({where:{status:'PENDING',due_at:{lte:now}},orderBy:{due_at:'asc'},take:200});for(const d of pending){const state=await resourceAllowed(d);const tooOld=d.due_at.getTime()<now.getTime()-CATCH_UP_MS;const quiet=state.pref?inQuietHours(localTimeKey(now,state.pref.timezone),state.pref.quiet_hours_start,state.pref.quiet_hours_end):false;const status=!state.allowed||tooOld||quiet?'SUPPRESSED':simulateFailure?'FAILED':'DELIVERED';await prisma.notification_deliveries.update({where:{id:d.id},data:{status,attempt_count:{increment:1},delivered_at:status==='DELIVERED'?now:null,failure_code:status==='FAILED'?'CHANNEL_UNAVAILABLE':null,updated_at:now}})}}
export async function runSchedulerOnce(now=new Date(),options:{simulateDeliveryFailure?:boolean}={}){const lock=await prisma.$queryRaw<Array<{locked:boolean}>>`SELECT pg_try_advisory_lock(${LOCK_ID}) AS locked`;if(!lock[0]?.locked)return{locked:false};try{await generateOccurrences(now);await generateControlDeliveries(now);await evaluateOverdueControlSchedules(now);await prisma.medication_occurrences.updateMany({where:{status:'SNOOZED',snooze_until:{lte:now}},data:{status:'PENDING',updated_at:now}});await prisma.medication_occurrences.updateMany({where:{status:'PENDING',scheduled_at:{lt:new Date(now.getTime()-6*3600_000)}},data:{status:'MISSED',responded_at:now,updated_at:now}});await deliver(now,options.simulateDeliveryFailure);return{locked:true}}finally{await prisma.$queryRaw`SELECT pg_advisory_unlock(${LOCK_ID})`}}
export function startHealthScheduler(){const run=()=>void runSchedulerOnce().catch(()=>undefined);run();const timer=setInterval(run,60_000);timer.unref();return()=>clearInterval(timer)}
