const formatterCache=new Map<string,Intl.DateTimeFormat>();
export const SUPPORTED_DEFAULT_TIMEZONES=['Asia/Jayapura','Asia/Makassar','Asia/Jakarta'] as const;
export function isValidTimeZone(value:string){if(value.length<3||value.length>80)return false;try{new Intl.DateTimeFormat('en-US',{timeZone:value}).format();return true}catch{return false}}
function formatter(timeZone:string){let f=formatterCache.get(timeZone);if(!f){f=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});formatterCache.set(timeZone,f)}return f}
export function localParts(date:Date,timeZone:string){const parts=Object.fromEntries(formatter(timeZone).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));return{year:parts.year,month:parts.month,day:parts.day,hour:parts.hour,minute:parts.minute,second:parts.second}}
export function localDateKey(date:Date,timeZone:string){const p=localParts(date,timeZone);return`${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`}
export function localTimeKey(date:Date,timeZone:string){const p=localParts(date,timeZone);return`${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')}`}
export function localDateTimeToUtc(dateKey:string,timeKey:string,timeZone:string){if(!isValidTimeZone(timeZone)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(dateKey)||!/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(timeKey))throw new Error('Invalid local date/time');const[y,m,d]=dateKey.split('-').map(Number);const[hour,minute]=timeKey.split(':').map(Number);const target=Date.UTC(y,m-1,d,hour,minute,0);let candidate=target;for(let i=0;i<4;i++){const p=localParts(new Date(candidate),timeZone);const represented=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);const delta=target-represented;if(delta===0)return new Date(candidate);candidate+=delta}const result=new Date(candidate);const p=localParts(result,timeZone);if(p.year!==y||p.month!==m||p.day!==d||p.hour!==hour||p.minute!==minute)throw new Error('Local time does not exist in timezone');return result}
export function addLocalDays(dateKey:string,days:number){const[y,m,d]=dateKey.split('-').map(Number);return new Date(Date.UTC(y,m-1,d+days,12)).toISOString().slice(0,10)}
export function weekday(dateKey:string){return new Date(`${dateKey}T12:00:00.000Z`).getUTCDay()}
export function inQuietHours(time:string,start?:string|null,end?:string|null){if(!start||!end||start===end)return false;return start<end?time>=start&&time<end:time>=start||time<end}
