import type { FormHTMLAttributes, ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { cn } from '../../lib/utils';
import { Badge, type BadgeVariant } from './badge';
import { buttonClassName } from './button';
import { Icon, type IconName } from './icons';

export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="max-w-3xl">{eyebrow?<p className="eyebrow">{eyebrow}</p>:null}<h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h1>{description?<p className="mt-2 text-sm leading-6 text-slate-600 sm:text-base">{description}</p>:null}</div>{action}</header>}
export function HeroCard({eyebrow,title,description,action,secondary,icon='heart',tone='calm'}:{eyebrow?:string;title:string;description:string;action?:ReactNode;secondary?:ReactNode;icon?:IconName;tone?:'calm'|'warm'|'support'}){const tones={calm:'from-sky-50 via-white to-cyan-50 border-sky-100',warm:'from-rose-50 via-white to-orange-50 border-rose-100',support:'from-violet-50 via-white to-sky-50 border-violet-100'};return <section className={cn('relative overflow-hidden rounded-[1.75rem] border bg-gradient-to-br p-6 shadow-[0_20px_60px_rgba(15,35,61,.08)] sm:p-8',tones[tone])}><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-white/60"/><div className="relative flex max-w-3xl items-start gap-4"><span className="hidden rounded-2xl bg-white p-3 text-brand shadow-sm sm:inline-flex"><Icon name={icon} className="h-7 w-7"/></span><div>{eyebrow?<p className="eyebrow">{eyebrow}</p>:null}<h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">{description}</p>{action||secondary?<div className="mt-5 flex flex-wrap gap-3">{action}{secondary}</div>:null}</div></div></section>}
export function ActionCard({icon,title,description,href,action='Buka',tone='calm'}:{icon:IconName;title:string;description:string;href:string;action?:string;tone?:'calm'|'warm'|'support'|'mint'}){const tones={calm:'bg-sky-50 text-sky-800',warm:'bg-rose-50 text-rose-800',support:'bg-violet-50 text-violet-800',mint:'bg-emerald-50 text-emerald-800'};return <article className="group flex h-full flex-col rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-200 hover:shadow-lg motion-reduce:transform-none"><span className={cn('inline-flex h-11 w-11 items-center justify-center rounded-xl',tones[tone])}><Icon name={icon}/></span><h3 className="mt-4 text-lg font-bold text-slate-950">{title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{description}</p><Link to={href} className="mt-4 inline-flex min-h-11 items-center gap-1 font-semibold text-brand hover:underline">{action}<Icon name="chevron" className="h-4 w-4"/></Link></article>}
export function StatusBadge({children,variant='info'}:{children:ReactNode;variant?:BadgeVariant}){return <Badge variant={variant} className="gap-1.5"><span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-current"/>{children}</Badge>}
export function EmptyState({title,description,actionHref,actionLabel,icon='clipboard'}:{title:string;description:string;actionHref?:string;actionLabel?:string;icon?:IconName}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50/70 px-5 py-10 text-center"><span className="mx-auto inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-slate-500 shadow-sm"><Icon name={icon}/></span><h3 className="mt-4 font-bold text-slate-900">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">{description}</p>{actionHref&&actionLabel?<Link to={actionHref} className={buttonClassName({variant:'outline',className:'mt-5'})}>{actionLabel}</Link>:null}</div>}
export function Skeleton({className}:{className?:string}){return <div role="status" aria-label="Memuat" className={cn('animate-pulse rounded-xl bg-slate-200 motion-reduce:animate-none',className)}/>}
export function StatCard({label,value,description,icon='activity'}:{label:string;value:ReactNode;description?:string;icon?:IconName}){return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p>{description?<p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>:null}</div><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-sky-50 text-brand"><Icon name={icon}/></span></div></div>}
export function ErrorState({title='Terjadi kendala',description,onRetry}:{title?:string;description:string;onRetry?:()=>void}){return <div role="alert" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><div className="flex gap-3"><Icon name="help" className="h-5 w-5 shrink-0"/><div><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6">{description}</p>{onRetry?<button type="button" onClick={onRetry} className={buttonClassName({variant:'outline',size:'sm',className:'mt-3 bg-white'})}>Coba lagi</button>:null}</div></div></div>}
export function FilterBar({children,className,...props}:FormHTMLAttributes<HTMLFormElement>){return <form className={cn('grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 lg:flex lg:items-end',className)} {...props}>{children}</form>}
export type DataColumn<T>={key:string;header:string;render:(row:T,mode?:'table'|'card')=>ReactNode};
export function DataTable<T>({caption,rows,columns,rowKey,empty}:{caption:string;rows:T[];columns:DataColumn<T>[];rowKey:(row:T)=>string;empty?:ReactNode}){if(!rows.length)return <>{empty??<EmptyState title="Belum ada data" description="Data yang tersedia akan muncul di sini."/>}</>;return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-slate-50 text-slate-600"><tr>{columns.map(column=><th key={column.key} scope="col" className="px-5 py-3 font-bold">{column.header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row=><tr key={rowKey(row)}>{columns.map(column=><td key={column.key} className="px-5 py-4 align-top">{column.render(row,'table')}</td>)}</tr>)}</tbody></table></div><ul className="divide-y divide-slate-100 md:hidden" aria-label={caption}>{rows.map(row=><li key={rowKey(row)} className="space-y-3 p-5">{columns.map(column=><div key={column.key} className="grid grid-cols-[7rem_1fr] gap-3 text-sm"><span className="font-bold text-slate-500">{column.header}</span><span><span className="sr-only">Ringkasan: </span>{column.render(row,'card')}</span></div>)}</li>)}</ul></div>}
export function FloatingActionButton({label,onClick,icon='chat'}:{label:string;onClick:()=>void;icon?:IconName}){return <button type="button" aria-label={label} onClick={onClick} className="inline-flex min-h-14 items-center gap-2 rounded-full bg-empathy px-5 py-3 font-bold text-white shadow-xl hover:bg-rose-700 focus:ring-4 focus:ring-rose-100"><Icon name={icon}/><span>{label}</span></button>}
