import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import bcrypt from 'bcryptjs';
import { buildApp } from '../src/app';
import { prisma } from '../src/db/prisma';
import { runStage4SchedulerOnce } from '../src/modules/stage4/stage4.scheduler';

test('stage 4 counselor and complaint lifecycle, authorization, SLA, deduplication, and failures', async () => {
  const app=await buildApp(); const marker=randomUUID(); const password='Stage4-fixture-2026';
  const roles=['PASIEN','PASIEN','COUNSELOR','COUNSELOR','COMPLAINT_OFFICER','COMPLAINT_OFFICER','SUPERVISOR','ADMIN'] as const;
  const users=await Promise.all(roles.map(async(role,index)=>prisma.users.create({data:{id:randomUUID(),email:`stage4-${index}-${marker}@example.test`,full_name:`DATA UJI ${role} ${index}`,display_alias:`Alias Uji ${index}`,role,password_hash:await bcrypt.hash(password,4),updated_at:new Date()}})));
  const [patientA,patientB,counselorA,counselorB,officerA,officerB,supervisor,admin]=users;
  await prisma.counselor_profiles.createMany({data:[counselorA,counselorB].map(counselor=>({user_id:counselor.id,permission_enabled:true,verification_status:'VERIFIED',professional_name:counselor.full_name,profession:'Konselor DATA UJI',competencies:['GENERAL'],languages:['Bahasa Indonesia'],active_days:[0,1,2,3,4,5,6],opens_at:'00:00',closes_at:'23:59',timezone:'Asia/Jayapura',is_available:true,max_active_conversations:10,is_active:true,verified_at:new Date(),verified_by:admin.id,updated_at:new Date()}))});
  await prisma.counselor_applications.createMany({data:[counselorA,counselorB].map(counselor=>({id:randomUUID(),user_id:counselor.id,status:'ACTIVE',professional_name:counselor.full_name,profession:'Konselor DATA UJI',competencies:['GENERAL'],languages:['Bahasa Indonesia'],active_days:[0,1,2,3,4,5,6],opens_at:'00:00',closes_at:'23:59',timezone:'Asia/Jayapura',submitted_at:new Date(),reviewed_at:new Date(),verified_at:new Date(),activated_at:new Date(),updated_at:new Date()}))});
  const headers=users.map(u=>({authorization:`Bearer ${app.auth.signAccessToken({userId:u.id,role:u.role,sessionVersion:u.session_version})}`}));
  const [pa,pb,ca,cb,oa,ob,sv,ad]=headers;
  try {
    const created=await app.inject({method:'POST',url:'/counselor-conversations',headers:pa,payload:{service_type:'COUNSELOR',subject:'Dukungan DATA UJI',initial_message:'Pesan awal sintetis aman',priority:1,user_id:patientB.id}});
    assert.equal(created.statusCode,201,created.body); const conversationId=created.json().public_id;
    const stored=await prisma.service_conversations.findUniqueOrThrow({where:{public_id:conversationId}}); assert.equal(stored.user_id,patientA.id);
    assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${conversationId}`,headers:pb})).statusCode,404);
    assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${conversationId}`,headers:ad})).statusCode,403);
    assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${conversationId}`,headers:ca})).statusCode,404);
    const claims=await Promise.all([app.inject({method:'POST',url:`/counselor/conversations/${conversationId}/assign`,headers:ca,payload:{}}),app.inject({method:'POST',url:`/counselor/conversations/${conversationId}/assign`,headers:cb,payload:{}})]);
    assert.deepEqual(claims.map(x=>x.statusCode).sort(),[200,409]); const assigned=(await prisma.service_conversations.findUniqueOrThrow({where:{public_id:conversationId}})).assigned_counselor_id!; const assignedHeader=assigned===counselorA.id?ca:cb; const otherHeader=assigned===counselorA.id?cb:ca;
    assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${conversationId}`,headers:assignedHeader})).statusCode,200);
    assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${conversationId}`,headers:otherHeader})).statusCode,404);
    const idem='message_key_stage4'; const first=await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/messages`,headers:pa,payload:{content:'Pesan DATA UJI yang dideduplikasi',idempotency_key:idem,sender_id:patientB.id}}); const duplicate=await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/messages`,headers:pa,payload:{content:'Pesan DATA UJI yang dideduplikasi',idempotency_key:idem}}); assert.equal(first.statusCode,201,first.body);assert.equal(duplicate.json().public_id,first.json().public_id);
    const reply=await app.inject({method:'POST',url:`/counselor/conversations/${conversationId}/reply`,headers:assignedHeader,payload:{content:'Balasan rahasia DATA UJI',idempotency_key:'counselor_reply_stage4'}});assert.equal(reply.statusCode,201,reply.body);
    const notification=await prisma.notification_deliveries.findFirstOrThrow({where:{user_id:patientA.id,kind:'NEW_MESSAGE'},orderBy:{created_at:'desc'}});assert.equal(notification.neutral_text,'Anda memiliki pesan baru.');assert.doesNotMatch(JSON.stringify(notification),/Balasan rahasia/);
    await app.inject({method:'GET',url:`/counselor-conversations/${conversationId}`,headers:pa}); const read=await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/read`,headers:pa}); assert.equal(read.statusCode,200); assert.ok((await prisma.message_receipts.count({where:{read_at:{not:null},participant_id:patientA.id}}))>0);
    const report=await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/report`,headers:pa,payload:{message_public_id:reply.json().public_id,reason:'OTHER',description:'Laporan DATA UJI'}});assert.equal(report.statusCode,201,report.body);const reportId=report.json().public_id;assert.equal((await app.inject({method:'GET',url:`/admin/conversation-reports/${reportId}`,headers:pa})).statusCode,403);const reportDetail=await app.inject({method:'GET',url:`/admin/conversation-reports/${reportId}`,headers:sv});assert.equal(reportDetail.statusCode,200,reportDetail.body);const assignedReport=await app.inject({method:'POST',url:`/admin/conversation-reports/${reportId}/assign`,headers:sv,payload:{reviewer_public_id:supervisor.public_id,reason:'DATA UJI: mengambil tugas review.'}});assert.equal(assignedReport.statusCode,200,assignedReport.body);const reportContext=await app.inject({method:'POST',url:`/admin/conversation-reports/${reportId}/context`,headers:sv,payload:{reason:'DATA UJI: konteks diperlukan untuk review.'}});assert.equal(reportContext.statusCode,200,reportContext.body);const resolvedReport=await app.inject({method:'POST',url:`/admin/conversation-reports/${reportId}/action`,headers:sv,payload:{action:'RESOLVE',reason:'DATA UJI: laporan telah ditinjau.'}});assert.equal(resolvedReport.statusCode,200,resolvedReport.body);
    const block=await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/block`,headers:pa,payload:{reason:'Preferensi pengguna'}});assert.equal(block.statusCode,200,block.body);assert.equal(block.json().service_access_available,true);
    assert.equal((await app.inject({method:'POST',url:`/counselor/conversations/${conversationId}/assign`,headers:assignedHeader,payload:{}})).statusCode,409);
    assert.equal((await app.inject({method:'POST',url:`/counselor/conversations/${conversationId}/assign`,headers:otherHeader,payload:{}})).statusCode,200);
    assert.equal((await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/voice-notes/upload-url`,headers:pa,payload:{content_type:'text/plain',file_size_bytes:20,duration_seconds:1}})).statusCode,400);
    assert.equal((await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/close`,headers:pa,payload:{}})).statusCode,200);
    assert.equal((await app.inject({method:'POST',url:`/counselor-conversations/${conversationId}/messages`,headers:pa,payload:{content:'Tidak boleh terkirim',idempotency_key:'closed_message_key'}})).statusCode,409);

    const anon=await app.inject({method:'POST',url:'/complaints',payload:{category:'PRIVACY',subject:'Privasi DATA UJI',description:'Pengaduan anonim sintetis',priority:1,privacy_level:'ANONYMOUS',consent:true,submission_key:'anonymous_complaint_stage4'}});assert.equal(anon.statusCode,201,anon.body);assert.match(anon.json().tracking_secret,/^TRK-/);const anonStored=await prisma.complaint_tickets.findUniqueOrThrow({where:{public_id:anon.json().public_id}});assert.equal(anonStored.user_id,null);assert.notEqual(anonStored.tracking_secret_hash,anon.json().tracking_secret);
    assert.equal((await app.inject({method:'GET',url:`/complaints/track/${anon.json().tracking_code}`,headers:{'x-tracking-secret':'TRK-AAAAA-AAAAA-AAAAA'}})).statusCode,404);
    const tracked=await app.inject({method:'GET',url:`/complaints/track/${anon.json().tracking_code}`,headers:{'x-tracking-secret':anon.json().tracking_secret}});assert.equal(tracked.statusCode,200,tracked.body);assert.equal('tracking_secret_hash' in tracked.json(),false);const anonymousReply=await app.inject({method:'POST',url:`/complaints/track/${anon.json().tracking_code}/messages`,headers:{'x-tracking-secret':anon.json().tracking_secret},payload:{content:'Tambahan anonim DATA UJI',idempotency_key:'anonymous_reply_stage4'}});assert.equal(anonymousReply.statusCode,201,anonymousReply.body);const trackedAgain=await app.inject({method:'GET',url:`/complaints/track/${anon.json().tracking_code}`,headers:{'x-tracking-secret':anon.json().tracking_secret}});assert.match(trackedAgain.body,/Tambahan anonim DATA UJI/);
    const privateTicket=await app.inject({method:'POST',url:'/complaints',headers:pa,payload:{category:'SERVICE',subject:'Layanan DATA UJI',description:'Pengaduan privat sintetis',priority:2,privacy_level:'PRIVATE',consent:true,submission_key:'private_complaint_stage4',user_id:patientB.id}});assert.equal(privateTicket.statusCode,201,privateTicket.body);const ticketId=privateTicket.json().public_id;assert.equal((await prisma.complaint_tickets.findUniqueOrThrow({where:{public_id:ticketId}})).user_id,patientA.id);
    assert.equal((await app.inject({method:'GET',url:`/complaints/${ticketId}`,headers:pb})).statusCode,404);assert.equal((await app.inject({method:'GET',url:`/complaint-admin/${ticketId}`,headers:ad})).statusCode,403);
    const ticketClaims=await Promise.all([app.inject({method:'POST',url:`/complaint-admin/${ticketId}/assign`,headers:oa,payload:{}}),app.inject({method:'POST',url:`/complaint-admin/${ticketId}/assign`,headers:ob,payload:{}})]);assert.deepEqual(ticketClaims.map(x=>x.statusCode).sort(),[200,409]);const ticketStored=await prisma.complaint_tickets.findUniqueOrThrow({where:{public_id:ticketId}});const officerHeader=ticketStored.assigned_officer_id===officerA.id?oa:ob;const foreignOfficer=ticketStored.assigned_officer_id===officerA.id?ob:oa;
    assert.equal((await app.inject({method:'GET',url:`/complaint-admin/${ticketId}`,headers:foreignOfficer})).statusCode,404);
    const note=await app.inject({method:'POST',url:`/complaint-admin/${ticketId}/internal-note`,headers:officerHeader,payload:{content:'CATATAN INTERNAL RAHASIA DATA UJI',idempotency_key:'internal_note_stage4'}});assert.equal(note.statusCode,201,note.body);
    const userView=await app.inject({method:'GET',url:`/complaints/${ticketId}`,headers:pa});assert.equal(userView.statusCode,200,userView.body);assert.doesNotMatch(userView.body,/CATATAN INTERNAL RAHASIA/);
    const officerView=await app.inject({method:'GET',url:`/complaint-admin/${ticketId}`,headers:officerHeader});assert.match(officerView.body,/CATATAN INTERNAL RAHASIA/);
    const publicReply=await app.inject({method:'POST',url:`/complaint-admin/${ticketId}/reply`,headers:officerHeader,payload:{content:'Balasan publik untuk redaksi DATA UJI',idempotency_key:'public_redact_stage4'}});assert.equal(publicReply.statusCode,201,publicReply.body);assert.equal((await app.inject({method:'GET',url:'/stage4-governance/policy',headers:ad})).statusCode,403);assert.equal((await app.inject({method:'GET',url:'/stage4-governance/policy',headers:sv})).statusCode,200);const redact=await app.inject({method:'POST',url:`/stage4-governance/complaint-messages/${publicReply.json().public_id}/redact`,headers:sv,payload:{reason:'Permintaan redaksi DATA UJI'}});assert.equal(redact.statusCode,200,redact.body);assert.match((await app.inject({method:'GET',url:`/complaints/${ticketId}`,headers:pa})).body,/Pesan telah disunting/);assert.equal((await app.inject({method:'POST',url:`/stage4-governance/complaints/${ticketId}/restrict`,headers:sv,payload:{reason:'Pembatasan akses DATA UJI'}})).statusCode,200);assert.equal((await app.inject({method:'POST',url:'/stage4-data-deletion-requests',headers:pa,payload:{reason:'Permintaan penghapusan DATA UJI'}})).statusCode,202);assert.equal((await app.inject({method:'GET',url:'/stage4-governance/audits',headers:sv})).statusCode,200);assert.equal((await app.inject({method:'GET',url:'/stage4-governance/audits',headers:ad})).statusCode,403);
    assert.equal((await app.inject({method:'POST',url:`/complaints/${ticketId}/attachments/upload-url`,headers:pa,payload:{content_type:'text/plain',file_size_bytes:10}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:`/complaints/${ticketId}/attachments/upload-url`,headers:pa,payload:{content_type:'application/pdf',file_size_bytes:6*1024*1024}})).statusCode,400);
    assert.match(privateTicket.json().target_response_at,/Z$/);assert.match(privateTicket.json().target_response_local,/Asia\/Jayapura$/);assert.equal(privateTicket.json().sla_status,'ON_TRACK');
    await prisma.complaint_tickets.update({where:{public_id:ticketId},data:{resolution_due_at:new Date(Date.now()-60_000),response_due_at:new Date(Date.now()-60_000),status:'IN_REVIEW',escalation_level:0}});const scheduled=await runStage4SchedulerOnce(new Date());assert.equal(scheduled.locked,true);assert.equal(scheduled.escalated,1);assert.equal((await prisma.complaint_tickets.findUniqueOrThrow({where:{public_id:ticketId}})).status,'ESCALATED');
    assert.equal((await app.inject({method:'POST',url:'/complaints',payload:{category:'OTHER',subject:'<script>',description:'Unsafe DATA UJI',privacy_level:'ANONYMOUS',consent:true,submission_key:'unsafe_complaint_stage4'}})).statusCode,400);
    assert.ok(await prisma.sensitive_access_audits.count({where:{resource_public_id:{in:[conversationId,ticketId,anon.json().public_id]}}}));assert.equal((await app.inject({method:'GET',url:`/complaint-admin/${ticketId}`,headers:sv})).statusCode,200);
  } finally {
    const ids=users.map(u=>u.id);
    await prisma.sensitive_access_audits.deleteMany({where:{actor_user_id:{in:ids}}});
    const conversations=await prisma.service_conversations.findMany({where:{user_id:{in:ids}},select:{id:true}});const conversationIds=conversations.map(x=>x.id);const messages=await prisma.service_messages.findMany({where:{conversation_id:{in:conversationIds}},select:{id:true}});await prisma.message_receipts.deleteMany({where:{message_id:{in:messages.map(x=>x.id)}}});await prisma.conversation_reports.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.conversation_blocks.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.conversation_events.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.counselor_assignments.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.consultation_preferences.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.service_messages.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.service_conversations.deleteMany({where:{id:{in:conversationIds}}});
    const tickets=await prisma.complaint_tickets.findMany({where:{OR:[{user_id:{in:ids}},{submission_key:{in:['anonymous_complaint_stage4','private_complaint_stage4']}}]},select:{id:true,public_id:true}});const ticketIds=tickets.map(x=>x.id);await prisma.sensitive_access_audits.deleteMany({where:{resource_public_id:{in:tickets.map(x=>x.public_id)}}});await prisma.complaint_events.deleteMany({where:{ticket_id:{in:ticketIds}}});await prisma.complaint_messages.deleteMany({where:{ticket_id:{in:ticketIds}}});await prisma.complaint_assignments.deleteMany({where:{ticket_id:{in:ticketIds}}});await prisma.complaint_attachment_upload_sessions.deleteMany({where:{ticket_id:{in:ticketIds}}});await prisma.complaint_attachments.deleteMany({where:{ticket_id:{in:ticketIds}}});await prisma.complaint_tickets.deleteMany({where:{id:{in:ticketIds}}});await prisma.notification_deliveries.deleteMany({where:{user_id:{in:ids}}});await prisma.counselor_profiles.deleteMany({where:{user_id:{in:ids}}});await prisma.counselor_applications.deleteMany({where:{user_id:{in:ids}}});await prisma.refresh_tokens.deleteMany({where:{user_id:{in:ids}}});await prisma.users.deleteMany({where:{id:{in:ids}}});await app.close();
  }
});
