import test from 'node:test'; import assert from 'node:assert/strict'; import bcrypt from 'bcryptjs'; import { randomUUID } from 'node:crypto';
import { buildApp } from '../src/app'; import { prisma } from '../src/db/prisma';

test('stage 2 publication workflows, suppression, consent, RBAC, and facility filters', async()=>{
 const app=await buildApp(); const marker=randomUUID(); const adminId=randomUUID(); const patientId=randomUUID(); const email=`stage2-admin-${marker}@example.test`; const patientEmail=`stage2-patient-${marker}@example.test`; const ids:{stats:string[];articles:string[];videos:string[];consents:string[];facilities:string[]}={stats:[],articles:[],videos:[],consents:[],facilities:[]};
 try{
  await prisma.users.createMany({data:[{id:adminId,email,full_name:'Admin Stage 2',role:'ADMIN',password_hash:await bcrypt.hash('Admin-stage2-2026',12),updated_at:new Date()},{id:patientId,email:patientEmail,full_name:'Pasien Stage 2',role:'PASIEN',password_hash:await bcrypt.hash('Patient-stage2-2026',12),updated_at:new Date()}]});
  const login=await app.inject({method:'POST',url:'/auth/login',payload:{email,password:'Admin-stage2-2026'}});assert.equal(login.statusCode,200,login.body);const token=login.json().access_token;
  const patientLogin=await app.inject({method:'POST',url:'/auth/login',payload:{email:patientEmail,password:'Patient-stage2-2026'}});const patientToken=patientLogin.json().access_token;
  assert.equal((await app.inject({method:'GET',url:'/admin/content/overview',headers:{authorization:`Bearer ${patientToken}`}})).statusCode,403);
  const region=await prisma.regions.findFirstOrThrow({where:{code:'82.71'}}); const category=await prisma.content_categories.findFirstOrThrow({where:{slug:'edukasi-dasar'}}); const headers={authorization:`Bearer ${token}`};
  const invalidStat=await app.inject({method:'POST',url:'/admin/content/statistics',headers,payload:{region_id:region.id,period_start:'2099-01-01',period_end:'2099-12-31',year:2099,period_type:'YEARLY',case_count:-1,data_category:'DATA UJI',source_name:'DATA UJI',updated_on:'2099-12-31',is_sample:true}});assert.equal(invalidStat.statusCode,400,invalidStat.body);
  const stat=await app.inject({method:'POST',url:'/admin/content/statistics',headers,payload:{region_id:region.id,period_start:'2099-01-01',period_end:'2099-12-31',year:2099,period_type:'YEARLY',case_count:2,data_category:'DATA UJI',source_name:'DATA UJI',source_url:'https://example.org/source',updated_on:'2099-12-31',is_sample:true}});assert.equal(stat.statusCode,201,stat.body);ids.stats.push(stat.json().id);
  assert.equal((await app.inject({method:'GET',url:'/public/statistics?year=2099'})).json().total,0);
  assert.equal((await app.inject({method:'PUT',url:`/admin/content/statistics/${stat.json().id}/status`,headers,payload:{status:'PUBLISHED'}})).statusCode,200);
  const publicStat=(await app.inject({method:'GET',url:'/public/statistics?year=2099'})).json().items[0];assert.equal(publicStat.case_count,null);assert.equal(publicStat.count_suppressed,true);assert.equal('created_by' in publicStat,false);
  const unsafe=await app.inject({method:'POST',url:'/admin/content/articles',headers,payload:{title:'Unsafe',slug:`unsafe-${marker}`,summary:'Ringkasan',body_markdown:'<script>alert(1)</script>',category_id:category.id,language:'id',source_reference:'https://example.org/source',reading_minutes:2,featured:false}});assert.equal(unsafe.statusCode,400);
  const article=await app.inject({method:'POST',url:'/admin/content/articles',headers,payload:{title:'Artikel DATA UJI',slug:`artikel-${marker}`,summary:'Ringkasan aman DATA UJI',body_markdown:'Isi aman dan tanpa data pribadi.',category_id:category.id,language:'id',source_reference:'https://example.org/source',reading_minutes:2,featured:false}});assert.equal(article.statusCode,201,article.body);ids.articles.push(article.json().id);assert.equal((await app.inject({method:'GET',url:`/public/articles/${article.json().slug}`})).statusCode,404);await app.inject({method:'PUT',url:`/admin/content/articles/${article.json().id}/status`,headers,payload:{status:'PUBLISHED'}});assert.equal((await app.inject({method:'GET',url:`/public/articles/${article.json().slug}`})).statusCode,200);
  const badVideo=await app.inject({method:'POST',url:'/admin/content/videos',headers,payload:{title:'Bad',description:'Bad host',source_type:'EXTERNAL',external_url:'https://evil.example/video',thumbnail_alt:'Gambar',language:'id',subtitle_text:'Subtitle',transcript_text:'Transkrip',speaker_type:'GENERAL'}});assert.equal(badVideo.statusCode,400);
  const video=await app.inject({method:'POST',url:'/admin/content/videos',headers,payload:{title:'Video DATA UJI',description:'Metadata sintetis',category_id:category.id,source_type:'EXTERNAL',external_url:'https://www.youtube.com/watch?v=DATA_UJI',thumbnail_alt:'Ilustrasi DATA UJI',duration_seconds:60,language:'id',subtitle_text:'Subtitle DATA UJI',transcript_text:'Transkrip DATA UJI',speaker_type:'ODHIV_OPEN'}});assert.equal(video.statusCode,201,video.body);ids.videos.push(video.json().id);const blocked=await app.inject({method:'PUT',url:`/admin/content/videos/${video.json().id}/status`,headers,payload:{status:'PUBLISHED'}});assert.equal(blocked.statusCode,400);
  const consent=await app.inject({method:'POST',url:`/admin/content/videos/${video.json().id}/consents`,headers,payload:{subject_type:'PERSON',subject_reference:`sub_${marker.replace(/-/g,'').slice(0,16)}`,consent_version:'v1',scope:'Publikasi edukasi DATA UJI'}});assert.equal(consent.statusCode,201,consent.body);ids.consents.push(consent.json().id);assert.equal((await app.inject({method:'PUT',url:`/admin/content/consents/${consent.json().id}/status`,headers,payload:{status:'APPROVED'}})).statusCode,400);
  await prisma.media_consents.update({where:{id:consent.json().id},data:{status:'APPROVED',approved_at:new Date(),reviewed_by:adminId,updated_at:new Date()}});assert.equal((await app.inject({method:'PUT',url:`/admin/content/videos/${video.json().id}/status`,headers,payload:{status:'PUBLISHED'}})).statusCode,200);const publicVideo=await app.inject({method:'GET',url:`/public/videos/${video.json().id}`});assert.equal(publicVideo.statusCode,200);assert.equal(JSON.stringify(publicVideo.json()).includes('subject_reference'),false);assert.equal(JSON.stringify(publicVideo.json()).includes('consent'),false);
  await app.inject({method:'PUT',url:`/admin/content/consents/${consent.json().id}/status`,headers,payload:{status:'WITHDRAWN'}});assert.equal((await app.inject({method:'GET',url:`/public/videos/${video.json().id}`})).statusCode,404);
  const facility=await app.inject({method:'POST',url:'/admin/content/facilities',headers,payload:{name:`Klinik DATA UJI ${marker.slice(0,8)}`,facility_type:'KLINIK',region_id:region.id,address:'Alamat DATA UJI',service_hours:'Senin–Jumat',source_name:'DATA UJI',is_sample:true,services:['HIV_TESTING','DISABILITY_ACCESS']}});assert.equal(facility.statusCode,201,facility.body);ids.facilities.push(facility.json().id);assert.equal((await app.inject({method:'GET',url:`/public/facilities?q=${marker.slice(0,8)}`})).json().total,0);await app.inject({method:'PUT',url:`/admin/content/facilities/${facility.json().id}/status`,headers,payload:{status:'VERIFIED'}});assert.equal((await app.inject({method:'GET',url:`/public/facilities?q=${marker.slice(0,8)}&service=HIV_TESTING`})).json().total,1);assert.equal((await app.inject({method:'GET',url:`/public/facilities?q=${marker.slice(0,8)}&service=PHARMACY`})).json().total,0);
 }finally{
  await prisma.facility_services.deleteMany({where:{facility_id:{in:ids.facilities}}});await prisma.health_facilities.deleteMany({where:{id:{in:ids.facilities}}});await prisma.media_consents.deleteMany({where:{id:{in:ids.consents}}});await prisma.education_videos.deleteMany({where:{id:{in:ids.videos}}});await prisma.education_articles.deleteMany({where:{id:{in:ids.articles}}});await prisma.case_statistics.deleteMany({where:{id:{in:ids.stats}}});await prisma.audit_logs.deleteMany({where:{actor_user_id:{in:[adminId,patientId]}}});await prisma.refresh_tokens.deleteMany({where:{user_id:{in:[adminId,patientId]}}});await prisma.users.deleteMany({where:{id:{in:[adminId,patientId]}}});await app.close();await prisma.$disconnect();
 }
});
