import test from 'node:test'; import assert from 'node:assert/strict'; import bcrypt from 'bcryptjs'; import { randomUUID } from 'node:crypto';
import { buildApp } from '../src/app'; import { prisma } from '../src/db/prisma'; import { POLICY_VERSION } from '../src/modules/account/account.validators';

test('stage 1 anonymous lifecycle, recovery, legacy compatibility, and admin privacy', async () => {
 const app=await buildApp(); const marker=randomUUID(); const adminEmail=`stage1-admin-${marker}@example.test`; const adminId=randomUUID(); const legacyId=randomUUID(); const legacyEmail=`stage1-legacy-${marker}@example.test`; let anonymousId:string|undefined;
 const baseline=await prisma.users.count();
 try {
  await prisma.users.create({data:{id:adminId,email:adminEmail,full_name:'Admin Fixture',role:'ADMIN',password_hash:await bcrypt.hash('Admin-fixture-2026',12),updated_at:new Date()}});
  await prisma.users.create({data:{id:legacyId,email:legacyEmail,full_name:'Legacy Fixture',role:'PASIEN',password_hash:await bcrypt.hash('Legacy-fixture-2026',12),updated_at:new Date()}});
  const registration=await app.inject({method:'POST',url:'/auth/anonymous/register',payload:{alias:'Bintang Uji',password:'Anonim-aman-2026',password_confirmation:'Anonim-aman-2026',accept_terms:true,accept_privacy:true,policy_version:POLICY_VERSION,website:''}}); assert.equal(registration.statusCode,201,registration.body);
  const credentials=registration.json(); assert.ok(credentials.login_id); assert.ok(credentials.recovery_code); assert.ok(credentials.public_id); assert.equal('id' in credentials,false);
  const stored=await prisma.users.findUnique({where:{public_id:credentials.public_id}}); assert.ok(stored); anonymousId=stored!.id; assert.notEqual(stored!.password_hash,'Anonim-aman-2026'); assert.notEqual(stored!.recovery_code_hash,credentials.recovery_code); assert.equal(stored!.email,null); assert.equal(stored!.phone_e164,null);
  assert.equal(await prisma.account_consents.count({where:{user_id:stored!.id}}),2);
  const login=await app.inject({method:'POST',url:'/auth/anonymous/login',payload:{login_id:credentials.login_id,password:'Anonim-aman-2026'}}); assert.equal(login.statusCode,200,login.body); const token=login.json().access_token; assert.equal(login.json().user.id,credentials.public_id); assert.equal(JSON.stringify(login.json()).includes(stored!.id),false);
  const profile=await app.inject({method:'GET',url:'/account/profile',headers:{authorization:`Bearer ${token}`}}); assert.equal(profile.statusCode,200,profile.body); assert.equal(profile.json().email,undefined);
  const recovery=await app.inject({method:'POST',url:'/auth/anonymous/recover',payload:{login_id:credentials.login_id,recovery_code:credentials.recovery_code,new_password:'Anonim-baru-2026',password_confirmation:'Anonim-baru-2026'}}); assert.equal(recovery.statusCode,200,recovery.body); assert.notEqual(recovery.json().recovery_code,credentials.recovery_code);
  const stale=await app.inject({method:'GET',url:'/account/profile',headers:{authorization:`Bearer ${token}`}}); assert.equal(stale.statusCode,401);
  assert.equal((await app.inject({method:'POST',url:'/auth/anonymous/login',payload:{login_id:credentials.login_id,password:'Anonim-aman-2026'}})).statusCode,401);
  assert.equal((await app.inject({method:'POST',url:'/auth/anonymous/login',payload:{login_id:credentials.login_id,password:'Anonim-baru-2026'}})).statusCode,200);
  const adminLogin=await app.inject({method:'POST',url:'/auth/login',payload:{email:adminEmail,password:'Admin-fixture-2026'}}); assert.equal(adminLogin.statusCode,200,adminLogin.body); const adminToken=adminLogin.json().access_token;
  const legacyLogin=await app.inject({method:'POST',url:'/auth/login',payload:{email:legacyEmail,password:'Legacy-fixture-2026'}}); assert.equal(legacyLogin.statusCode,200,legacyLogin.body); const beforeConvert=await prisma.users.count();
  const conversion=await app.inject({method:'POST',url:'/account/convert-anonymous',headers:{authorization:`Bearer ${legacyLogin.json().access_token}`},payload:{alias:'Ombak Uji',current_password:'Legacy-fixture-2026',password:'Legacy-anonim-2026',password_confirmation:'Legacy-anonim-2026',accept_terms:true,accept_privacy:true,policy_version:POLICY_VERSION}}); assert.equal(conversion.statusCode,200,conversion.body); assert.equal(await prisma.users.count(),beforeConvert); assert.equal((await app.inject({method:'POST',url:'/auth/login',payload:{email:legacyEmail,password:'Legacy-anonim-2026'}})).statusCode,401); assert.equal((await app.inject({method:'POST',url:'/auth/anonymous/login',payload:{login_id:conversion.json().login_id,password:'Legacy-anonim-2026'}})).statusCode,200);
  const list=await app.inject({method:'GET',url:`/admin/users?search=${encodeURIComponent(credentials.public_id)}`,headers:{authorization:`Bearer ${adminToken}`}}); assert.equal(list.statusCode,200,list.body); const body=list.json(); assert.equal(body.items.length,1); assert.equal(JSON.stringify(body).includes(credentials.login_id),false); assert.equal(JSON.stringify(body).includes('recovery'),false); assert.equal(JSON.stringify(body).includes('@example.test'),false);
  const disable=await app.inject({method:'PUT',url:`/admin/users/${credentials.public_id}/status`,headers:{authorization:`Bearer ${adminToken}`},payload:{is_active:false}}); assert.equal(disable.statusCode,200,disable.body);
  assert.equal((await app.inject({method:'POST',url:'/auth/anonymous/login',payload:{login_id:credentials.login_id,password:'Anonim-baru-2026'}})).statusCode,401);
 } finally {
  const ids=[adminId,legacyId,...(anonymousId?[anonymousId]:[])]; await prisma.refresh_tokens.deleteMany({where:{user_id:{in:ids}}}); await prisma.account_consents.deleteMany({where:{user_id:{in:ids}}}); await prisma.audit_logs.deleteMany({where:{OR:[{actor_user_id:{in:ids}},{entity_id:{in:ids}}]}}); await prisma.users.deleteMany({where:{id:{in:ids}}}); await app.close(); assert.equal(await prisma.users.count(),baseline); await prisma.$disconnect();
 }
});
