import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import bcrypt from 'bcryptjs';
import { buildApp } from '../src/app';
import { prisma } from '../src/db/prisma';

test('Ayo Curhat unifies recommendation, assignment, history, permissions, chat, receipts, and privacy',async()=>{
  const app=await buildApp();const marker=randomUUID();const password='Unified-fixture-2026';
  const admin=await prisma.users.create({data:{id:randomUUID(),email:`unified-admin-${marker}@example.test`,full_name:'Admin DATA UJI',role:'ADMIN',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const patientA=await prisma.users.create({data:{id:randomUUID(),login_id:`SC-${marker.slice(0,4)}-AAAA-BBBB`.toUpperCase(),full_name:'Pasien anonim DATA UJI',display_alias:'Pasien Uji',account_mode:'ANONYMOUS',role:'PASIEN',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const patientB=await prisma.users.create({data:{id:randomUUID(),email:`unified-patient-${marker}@example.test`,full_name:'Pasien B DATA UJI',role:'PASIEN',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const patientC=await prisma.users.create({data:{id:randomUUID(),email:`unified-patient-c-${marker}@example.test`,full_name:'Pasien C DATA UJI',role:'PASIEN',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const doctor=await prisma.users.create({data:{id:randomUUID(),email:`unified-doctor-${marker}@example.test`,full_name:'Dokter Lama DATA UJI',role:'DOKTER',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const healthWorker=await prisma.users.create({data:{id:randomUUID(),email:`unified-counselor-${marker}@example.test`,full_name:'Perawat DATA UJI',role:'COUNSELOR',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const noPermission=await prisma.users.create({data:{id:randomUUID(),email:`unified-unpermitted-${marker}@example.test`,full_name:'Petugas Tanpa Izin DATA UJI',role:'COUNSELOR',password_hash:await bcrypt.hash(password,4),updated_at:new Date()}});
  const users=[admin,patientA,patientB,patientC,doctor,healthWorker,noPermission];const ids=users.map(user=>user.id);const now=new Date();
  const province=await prisma.regions.create({data:{id:randomUUID(),code:`UT-${marker.slice(0,6)}`,name:'Provinsi DATA UJI',type:'PROVINCE',updated_at:now}});
  const ternate=await prisma.regions.create({data:{id:randomUUID(),code:`UT-T-${marker.slice(0,5)}`,name:'Kota Ternate DATA UJI',type:'CITY_REGENCY',parent_id:province.id,updated_at:now}});
  const halteng=await prisma.regions.create({data:{id:randomUUID(),code:`UT-H-${marker.slice(0,5)}`,name:'Halmahera Tengah DATA UJI',type:'CITY_REGENCY',parent_id:province.id,updated_at:now}});
  const facilityTernate=await prisma.health_facilities.create({data:{id:randomUUID(),name:'Puskesmas Ternate DATA UJI',facility_type:'PUSKESMAS',region_id:ternate.id,address:'Alamat DATA UJI',service_hours:'Setiap hari',verification_status:'VERIFIED',verified_at:now,source_name:'DATA UJI',is_sample:true,updated_at:now}});
  const facilityHalteng=await prisma.health_facilities.create({data:{id:randomUUID(),name:'RS Halteng DATA UJI',facility_type:'RUMAH_SAKIT',region_id:halteng.id,address:'Alamat DATA UJI',service_hours:'Setiap hari',verification_status:'VERIFIED',verified_at:now,source_name:'DATA UJI',is_sample:true,updated_at:now}});
  await prisma.doctor_profiles.create({data:{user_id:doctor.id,verification_status:'VERIFIED',verified_at:now,verified_by:admin.id,updated_at:now}});
  const profile=(userId:string,name:string,profession:string,facilityId:string,regionId:string)=>({user_id:userId,permission_enabled:true,verification_status:'VERIFIED' as const,professional_name:name,profession,facility_id:facilityId,region_id:regionId,competencies:['GENERAL','EMOTIONAL_SUPPORT','SERVICE_ACCESS'],languages:['Bahasa Indonesia'],active_days:[0,1,2,3,4,5,6],opens_at:'00:00',closes_at:'23:59',timezone:'Asia/Jayapura',is_available:true,max_active_conversations:5,is_active:true,verified_at:now,verified_by:admin.id,updated_at:now});
  await prisma.counselor_profiles.createMany({data:[profile(doctor.id,'dr. Dokter Lama','Dokter',facilityTernate.id,ternate.id),profile(healthWorker.id,'Perawat Terlatih','Perawat',facilityHalteng.id,halteng.id)]});
  await prisma.counselor_applications.createMany({data:[
    {id:randomUUID(),user_id:doctor.id,status:'ACTIVE',professional_name:'dr. Dokter Lama',profession:'Dokter',facility_id:facilityTernate.id,region_id:ternate.id,competencies:['GENERAL','EMOTIONAL_SUPPORT','SERVICE_ACCESS'],languages:['Bahasa Indonesia'],active_days:[0,1,2,3,4,5,6],opens_at:'00:00',closes_at:'23:59',timezone:'Asia/Jayapura',submitted_at:now,reviewed_at:now,verified_at:now,activated_at:now,updated_at:now},
    {id:randomUUID(),user_id:healthWorker.id,status:'ACTIVE',professional_name:'Perawat Terlatih',profession:'Perawat',facility_id:facilityHalteng.id,region_id:halteng.id,competencies:['GENERAL','EMOTIONAL_SUPPORT','SERVICE_ACCESS'],languages:['Bahasa Indonesia'],active_days:[0,1,2,3,4,5,6],opens_at:'00:00',closes_at:'23:59',timezone:'Asia/Jayapura',submitted_at:now,reviewed_at:now,verified_at:now,activated_at:now,updated_at:now}
  ]});
  const header=(user:typeof patientA)=>({authorization:`Bearer ${app.auth.signAccessToken({userId:user.id,role:user.role,sessionVersion:user.session_version})}`});const pa=header(patientA),pb=header(patientB),pc=header(patientC),dr=header(doctor),hw=header(healthWorker),np=header(noPermission);
  const createdIds:string[]=[];
  try{
    const legacyLogin=await app.inject({method:'POST',url:'/auth/login',payload:{email:doctor.email,password}});assert.equal(legacyLogin.statusCode,200,legacyLogin.body);const doctorPermission=await app.inject({method:'GET',url:'/counselor/profile/me',headers:dr});assert.equal(doctorPermission.statusCode,200,doctorPermission.body);assert.equal(doctorPermission.json().enabled,true);const deniedPermission=await app.inject({method:'GET',url:'/counselor/profile/me',headers:np});assert.equal(deniedPermission.statusCode,200,deniedPermission.body);assert.equal(deniedPermission.json().enabled,false);
    const noLocation=await app.inject({method:'POST',url:'/consultation-counselors/recommendations',headers:pa,payload:{topic:'EMOTIONAL_SUPPORT'}});assert.equal(noLocation.statusCode,200,noLocation.body);const availableIds=noLocation.json().items.map((item:any)=>item.public_id);assert.ok(availableIds.includes(doctor.public_id));assert.ok(availableIds.includes(healthWorker.public_id));assert.doesNotMatch(noLocation.body,/password_hash|recovery_code_hash|phone_e164|@example\.test|user_id|storage_key/);
    const recommended=await app.inject({method:'POST',url:'/consultation-counselors/recommendations',headers:pa,payload:{topic:'EMOTIONAL_SUPPORT',region_id:ternate.id,facility_id:facilityTernate.id}});assert.equal(recommended.statusCode,200,recommended.body);assert.equal(recommended.json().recommended.public_id,doctor.public_id);assert.ok(recommended.json().recommended.reasons.includes('Berada di fasilitas pilihan'));
    const creationPayload={service_type:'COUNSELOR',subject:'Dukungan emosional',initial_message:'Cerita sintetis untuk pengujian terpadu',topic:'EMOTIONAL_SUPPORT',assignment_mode:'RECOMMENDED',region_id:ternate.id,facility_id:facilityTernate.id,submission_key:`recommended_${marker.replace(/-/g,'')}`};
    const created=await app.inject({method:'POST',url:'/counselor-conversations',headers:pa,payload:creationPayload});assert.equal(created.statusCode,201,created.body);createdIds.push(created.json().public_id);const duplicate=await app.inject({method:'POST',url:'/counselor-conversations',headers:pa,payload:creationPayload});assert.equal(duplicate.statusCode,200,duplicate.body);assert.equal(duplicate.json().public_id,created.json().public_id);
    const stored=await prisma.service_conversations.findUniqueOrThrow({where:{public_id:created.json().public_id},include:{preference:true,assignments:true}});assert.equal(stored.assigned_counselor_id,doctor.id);assert.equal(stored.preference?.assignment_mode,'RECOMMENDED');assert.equal(stored.assignments.length,1);
    const fastest=await app.inject({method:'POST',url:'/counselor-conversations',headers:pc,payload:{service_type:'COUNSELOR',initial_message:'Antrean tercepat DATA UJI',topic:'EMOTIONAL_SUPPORT',assignment_mode:'FASTEST',region_id:halteng.id,facility_id:facilityHalteng.id,submission_key:`fastest_${marker.replace(/-/g,'')}`}});assert.equal(fastest.statusCode,201,fastest.body);createdIds.push(fastest.json().public_id);const fastestStored=await prisma.service_conversations.findUniqueOrThrow({where:{public_id:fastest.json().public_id},include:{preference:true}});assert.equal(fastestStored.assigned_counselor_id,healthWorker.id);assert.equal(fastestStored.preference?.assignment_mode,'FASTEST');
    const selected=await app.inject({method:'POST',url:'/counselor-conversations',headers:pb,payload:{service_type:'COUNSELOR',initial_message:'Pilihan konselor DATA UJI',topic:'EMOTIONAL_SUPPORT',assignment_mode:'SELECTED',counselor_public_id:doctor.public_id,submission_key:`selected_${marker.replace(/-/g,'')}`}});assert.equal(selected.statusCode,201,selected.body);createdIds.push(selected.json().public_id);const selectedStored=await prisma.service_conversations.findUniqueOrThrow({where:{public_id:selected.json().public_id},include:{preference:true}});assert.equal(selectedStored.assigned_counselor_id,doctor.id);assert.equal(selectedStored.preference?.selected_counselor_id,doctor.id);
    await prisma.conversation_blocks.create({data:{id:randomUUID(),conversation_id:fastestStored.id,user_id:patientC.id,counselor_id:doctor.id,reason:'Fallback DATA UJI'}});const fallback=await app.inject({method:'POST',url:'/counselor-conversations',headers:pc,payload:{service_type:'COUNSELOR',initial_message:'Fallback fasilitas DATA UJI',topic:'SERVICE_ACCESS',assignment_mode:'FASTEST',region_id:ternate.id,facility_id:facilityTernate.id,submission_key:`fallback_${marker.replace(/-/g,'')}`}});assert.equal(fallback.statusCode,201,fallback.body);createdIds.push(fallback.json().public_id);assert.match(fallback.json().fallback_notice,/fasilitas pilihan/i);assert.equal((await prisma.service_conversations.findUniqueOrThrow({where:{public_id:fallback.json().public_id}})).assigned_counselor_id,healthWorker.id);
    assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${stored.public_id}`,headers:pb})).statusCode,404);assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${stored.public_id}`,headers:hw})).statusCode,404);assert.equal((await app.inject({method:'GET',url:'/counselor/queue',headers:np})).statusCode,403);assert.equal((await app.inject({method:'GET',url:`/counselor-conversations/${stored.public_id}`,headers:dr})).statusCode,200);
    const reply=await app.inject({method:'POST',url:`/counselor/conversations/${stored.public_id}/reply`,headers:dr,payload:{content:'Balasan aman DATA UJI',idempotency_key:`reply_${marker.slice(0,12)}`}});assert.equal(reply.statusCode,201,reply.body);await app.inject({method:'POST',url:`/counselor-conversations/${stored.public_id}/read`,headers:pa});const receiptCount=await prisma.message_receipts.count({where:{participant_id:patientA.id,read_at:{not:null}}});assert.ok(receiptCount>0);await app.inject({method:'POST',url:`/counselor-conversations/${stored.public_id}/read`,headers:pa});assert.equal(await prisma.message_receipts.count({where:{participant_id:patientA.id,read_at:{not:null}}}),receiptCount);
    const notice=await prisma.notification_deliveries.findFirstOrThrow({where:{user_id:patientA.id},orderBy:{created_at:'desc'}});assert.equal(notice.neutral_text,'Anda memiliki pesan baru.');assert.doesNotMatch(JSON.stringify(notice),/Balasan aman|Dukungan emosional|Ternate|Dokter Lama/);
    const legacy=await prisma.consultations.create({data:{id:randomUUID(),patient_id:patientA.id,status:'SELESAI',initial_complaint:'Riwayat lama DATA UJI',closed_at:now,updated_at:now}});const overview=await app.inject({method:'GET',url:'/consultation-overview',headers:pa});assert.equal(overview.statusCode,200,overview.body);assert.ok(overview.json().items.some((item:any)=>item.id===legacy.id));assert.ok(overview.json().items.some((item:any)=>item.id===stored.public_id));assert.ok(overview.json().items.every((item:any)=>!('source' in item)));
    await app.inject({method:'POST',url:`/counselor-conversations/${stored.public_id}/block`,headers:pa,payload:{reason:'DATA UJI'}});const afterBlock=await app.inject({method:'POST',url:'/consultation-counselors/recommendations',headers:pa,payload:{topic:'EMOTIONAL_SUPPORT'}});assert.equal(afterBlock.json().items.some((item:any)=>item.public_id===doctor.public_id),false);
    const queuePayload={service_type:'COUNSELOR',initial_message:'Antrean race DATA UJI',topic:'SERVICE_ACCESS',assignment_mode:'GENERAL_QUEUE',submission_key:`race_${marker.replace(/-/g,'')}`};const queued=await app.inject({method:'POST',url:'/counselor-conversations',headers:pb,payload:queuePayload});assert.equal(queued.statusCode,201,queued.body);createdIds.push(queued.json().public_id);const race=await Promise.all([app.inject({method:'POST',url:`/counselor/conversations/${queued.json().public_id}/assign`,headers:dr,payload:{}}),app.inject({method:'POST',url:`/counselor/conversations/${queued.json().public_id}/assign`,headers:hw,payload:{}})]);assert.deepEqual(race.map(result=>result.statusCode).sort(),[200,409]);
    const foreignVoice=await prisma.conversation_voice_notes.create({data:{id:randomUUID(),conversation_id:(await prisma.service_conversations.findUniqueOrThrow({where:{public_id:queued.json().public_id}})).id,uploaded_by:patientB.id,storage_key:`counselor-voice/${randomUUID()}.webm`,content_type:'audio/webm',file_size_bytes:32,duration_seconds:1}});assert.equal((await app.inject({method:'GET',url:`/counselor-voice-notes/${foreignVoice.public_id}`,headers:pa})).statusCode,404);
  }finally{
    const conversations=await prisma.service_conversations.findMany({where:{user_id:{in:[patientA.id,patientB.id,patientC.id]}},select:{id:true,public_id:true}});const conversationIds=conversations.map(row=>row.id);const messages=await prisma.service_messages.findMany({where:{conversation_id:{in:conversationIds}},select:{id:true}});
    await prisma.sensitive_access_audits.deleteMany({where:{actor_user_id:{in:ids}}});await prisma.notification_deliveries.deleteMany({where:{user_id:{in:ids}}});await prisma.message_receipts.deleteMany({where:{message_id:{in:messages.map(row=>row.id)}}});await prisma.conversation_reports.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.conversation_blocks.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.conversation_events.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.counselor_assignments.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.consultation_preferences.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.conversation_voice_notes.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.conversation_voice_upload_sessions.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.service_messages.deleteMany({where:{conversation_id:{in:conversationIds}}});await prisma.service_conversations.deleteMany({where:{id:{in:conversationIds}}});await prisma.consultation_participants.deleteMany({where:{user_id:{in:ids}}});await prisma.chat_messages.deleteMany({where:{consultations:{patient_id:{in:ids}}}});await prisma.consultations.deleteMany({where:{patient_id:{in:ids}}});await prisma.counselor_conflicts.deleteMany({where:{OR:[{patient_id:{in:ids}},{counselor_id:{in:ids}}]}});await prisma.counselor_profiles.deleteMany({where:{user_id:{in:ids}}});await prisma.counselor_applications.deleteMany({where:{user_id:{in:ids}}});await prisma.doctor_profiles.deleteMany({where:{user_id:doctor.id}});await prisma.refresh_tokens.deleteMany({where:{user_id:{in:ids}}});await prisma.health_facilities.deleteMany({where:{id:{in:[facilityTernate.id,facilityHalteng.id]}}});await prisma.regions.deleteMany({where:{id:{in:[ternate.id,halteng.id,province.id]}}});await prisma.users.deleteMany({where:{id:{in:ids}}});await app.close();
    assert.equal(await prisma.users.count({where:{id:{in:ids}}}),0);
  }
});
