import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import { rankEligibleCounselor } from '../src/modules/stage4/counselorMatching.service';

const baseProfile={
  user_id:'10000000-0000-4000-8000-000000000001',professional_name:'Dr. DATA UJI',profession:'Dokter',competencies:['EMOTIONAL_SUPPORT'],languages:['Bahasa Indonesia'],active_days:[3],opens_at:'08:00',closes_at:'17:00',timezone:'Asia/Jayapura',is_available:true,max_active_conversations:3,facility_id:'20000000-0000-4000-8000-000000000001',region_id:'30000000-0000-4000-8000-000000000001',user:{public_id:'usr_1234567890abcdef1234567890abcdef',role:'DOKTER',is_active:true,doctor_profiles_doctor_profiles_user_idTousers:{verification_status:'VERIFIED'}},facility:{id:'20000000-0000-4000-8000-000000000001',name:'Fasilitas DATA UJI',is_active:true,verification_status:'VERIFIED',region_id:'30000000-0000-4000-8000-000000000001',regions:{name:'Ternate',parent_id:'40000000-0000-4000-8000-000000000001'}},region:{id:'30000000-0000-4000-8000-000000000001',name:'Ternate',parent_id:'40000000-0000-4000-8000-000000000001'}
};
const now=new Date('2026-08-05T01:00:00.000Z'); // Wednesday, 10:00 Asia/Jayapura
function rank(overrides:Record<string,unknown>={},profileOverrides:Record<string,unknown>={}){return rankEligibleCounselor({profile:{...baseProfile,...profileOverrides} as never,topic:'EMOTIONAL_SUPPORT',workload:0,blocked:false,conflicted:false,requestedRegion:{id:baseProfile.region_id,parent_id:baseProfile.region.parent_id},requestedFacilityId:baseProfile.facility_id,now,...overrides} as never)}

test('verified counselor with matching competency, facility, hours, and capacity is explainably recommended',()=>{const result=rank();assert.equal(result.eligible,true);assert.equal(result.scope,'FACILITY');assert.ok(result.reasons.includes('Sesuai topik kebutuhan'));assert.ok(result.reasons.includes('Berada di fasilitas pilihan'))});
test('inactive, unavailable, unverified doctor, and nonmatching competency are rejected',()=>{assert.equal(rank({}, {is_available:false}).eligible,false);assert.equal(rank({}, {user:{...baseProfile.user,is_active:false}}).eligible,false);assert.equal(rank({}, {user:{...baseProfile.user,doctor_profiles_doctor_profiles_user_idTousers:{verification_status:'PENDING'}}}).eligible,false);assert.equal(rank({topic:'SERVICE_ACCESS'}).eligible,false)});
test('outside operational hours and full capacity are rejected',()=>{assert.equal(rank({now:new Date('2026-08-05T20:00:00.000Z')}).eligible,false);assert.equal(rank({workload:3}).eligible,false)});
test('blocking and conflicts are always honored',()=>{assert.equal(rank({blocked:true}).eligible,false);assert.equal(rank({conflicted:true}).eligible,false)});
test('migration is additive and preserves legacy data structures',()=>{const sql=readFileSync(join(process.cwd(),'prisma/migrations/20260805220000_unify_consultations_ayo_curhat/migration.sql'),'utf8');assert.doesNotMatch(sql,/\b(?:DROP|TRUNCATE|DELETE\s+FROM)\b/i);for(const table of ['consultations','chat_messages','voice_notes','service_conversations','service_messages','message_receipts','counselor_assignments'])assert.doesNotMatch(sql,new RegExp(`DROP\\s+TABLE\\s+"?${table}`,'i'))});
test('unified DTO source does not expose counselor private contacts or credentials',()=>{const source=readFileSync(join(process.cwd(),'src/modules/stage4/counselorMatching.service.ts'),'utf8');const dto=source.slice(source.indexOf('dto: {'),source.indexOf('recommendation_scope: ranked.scope')+40);for(const forbidden of ['password_hash','recovery_code_hash','email','phone_e164','storage_key','user_id: profile.user_id'])assert.equal(dto.includes(forbidden),false)});
test('patient creation uses Stage 4 conversation engine and an idempotent preference key',()=>{const source=readFileSync(join(process.cwd(),'src/modules/stage4/counselor.routes.ts'),'utf8');assert.match(source,/consultation_preferences\.findUnique\(\{where:\{submission_key/);assert.match(source,/service_conversations\.create/);assert.doesNotMatch(source.slice(source.indexOf("app.post('/counselor-conversations'"),source.indexOf("app.get('/counselor-conversations/:publicId'")),/consultations\.create/)});
test('doctor and non-doctor counselor access both require an enabled verified profile',()=>{const source=readFileSync(join(process.cwd(),'src/modules/stage4/counselor.routes.ts'),'utf8');assert.match(source,/profile\?\.permission_enabled/);assert.match(source,/profile\?\.verification_status==='VERIFIED'/);assert.match(source,/profile\.user\.role==='DOKTER'/);assert.match(source,/profile\.user\.role==='COUNSELOR'/)});
