CREATE TYPE "region_type" AS ENUM ('PROVINCE','CITY_REGENCY','DISTRICT');
CREATE TYPE "publication_status" AS ENUM ('DRAFT','REVIEW','PUBLISHED','ARCHIVED');
CREATE TYPE "period_type" AS ENUM ('MONTHLY','QUARTERLY','SEMESTER','YEARLY');
CREATE TYPE "video_source_type" AS ENUM ('UPLOAD','EXTERNAL');
CREATE TYPE "speaker_type" AS ENUM ('GENERAL','ODHIV_OPEN');
CREATE TYPE "consent_status" AS ENUM ('NOT_REQUIRED','PENDING','APPROVED','WITHDRAWN','EXPIRED');
CREATE TYPE "facility_type" AS ENUM ('PUSKESMAS','RUMAH_SAKIT','KLINIK');
CREATE TYPE "facility_verification_status" AS ENUM ('DRAFT','UNVERIFIED','VERIFIED','INACTIVE');
CREATE TYPE "facility_service_type" AS ENUM ('COUNSELING','HIV_TESTING','ARV_SERVICE','PSYCHOLOGY','LABORATORY','PHARMACY','DISABILITY_ACCESS','OTHER');

CREATE TABLE "regions" ("id" UUID NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"type" "region_type" NOT NULL,"parent_id" UUID,"is_active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "regions_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "regions_code_key" ON "regions"("code"); CREATE INDEX "regions_parent_id_is_active_idx" ON "regions"("parent_id","is_active"); CREATE INDEX "regions_name_idx" ON "regions"("name");
ALTER TABLE "regions" ADD CONSTRAINT "regions_parent_id_fkey" FOREIGN KEY("parent_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "content_categories" ("id" UUID NOT NULL,"slug" TEXT NOT NULL,"name" TEXT NOT NULL,"is_active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "content_categories_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "content_categories_slug_key" ON "content_categories"("slug");

ALTER TABLE "education_articles" ADD COLUMN "summary" TEXT NOT NULL DEFAULT '',ADD COLUMN "category_id" UUID,ADD COLUMN "thumbnail_key" TEXT,ADD COLUMN "thumbnail_alt" TEXT,ADD COLUMN "language" TEXT NOT NULL DEFAULT 'id',ADD COLUMN "reviewer_id" UUID,ADD COLUMN "publisher_id" UUID,ADD COLUMN "publication_status" "publication_status" NOT NULL DEFAULT 'DRAFT',ADD COLUMN "source_reference" TEXT,ADD COLUMN "reading_minutes" INTEGER NOT NULL DEFAULT 1,ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;
UPDATE "education_articles" SET "publication_status"='PUBLISHED',"summary"=left(regexp_replace("body_markdown", E'\\s+', ' ', 'g'),140) WHERE "is_published"=true;
ALTER TABLE "education_articles" ADD CONSTRAINT "education_articles_category_id_fkey" FOREIGN KEY("category_id") REFERENCES "content_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX "education_articles_publication_status_published_at_idx" ON "education_articles"("publication_status","published_at");

CREATE TABLE "case_statistics" ("id" UUID NOT NULL,"region_id" UUID NOT NULL,"period_start" TIMESTAMP(3) NOT NULL,"period_end" TIMESTAMP(3) NOT NULL,"year" INTEGER NOT NULL,"period_type" "period_type" NOT NULL,"case_count" INTEGER NOT NULL,"data_category" TEXT NOT NULL,"source_name" TEXT NOT NULL,"source_publication" TEXT,"source_url" TEXT,"updated_on" TIMESTAMP(3) NOT NULL,"methodology_note" TEXT,"publication_status" "publication_status" NOT NULL DEFAULT 'DRAFT',"is_sample" BOOLEAN NOT NULL DEFAULT false,"created_by" UUID,"reviewer_id" UUID,"publisher_id" UUID,"published_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "case_statistics_pkey" PRIMARY KEY("id"),CONSTRAINT "case_statistics_count_check" CHECK("case_count">=0),CONSTRAINT "case_statistics_period_check" CHECK("period_end">="period_start"));
ALTER TABLE "case_statistics" ADD CONSTRAINT "case_statistics_region_id_fkey" FOREIGN KEY("region_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; CREATE INDEX "case_statistics_publication_status_year_region_id_idx" ON "case_statistics"("publication_status","year","region_id"); CREATE INDEX "case_statistics_region_id_period_start_period_end_idx" ON "case_statistics"("region_id","period_start","period_end");

CREATE TABLE "education_videos" ("id" UUID NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"category_id" UUID,"source_type" "video_source_type" NOT NULL,"storage_key" TEXT,"external_url" TEXT,"thumbnail_key" TEXT,"thumbnail_alt" TEXT NOT NULL,"duration_seconds" INTEGER,"file_size_bytes" INTEGER,"language" TEXT NOT NULL DEFAULT 'id',"subtitle_text" TEXT NOT NULL,"transcript_text" TEXT NOT NULL,"speaker_type" "speaker_type" NOT NULL DEFAULT 'GENERAL',"publication_status" "publication_status" NOT NULL DEFAULT 'DRAFT',"created_by" UUID,"reviewer_id" UUID,"publisher_id" UUID,"published_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "education_videos_pkey" PRIMARY KEY("id"));
ALTER TABLE "education_videos" ADD CONSTRAINT "education_videos_category_id_fkey" FOREIGN KEY("category_id") REFERENCES "content_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE; CREATE INDEX "education_videos_publication_status_published_at_idx" ON "education_videos"("publication_status","published_at");

CREATE TABLE "media_consents" ("id" UUID NOT NULL,"media_id" UUID NOT NULL,"subject_type" TEXT NOT NULL,"subject_reference" TEXT NOT NULL,"consent_version" TEXT NOT NULL,"scope" TEXT NOT NULL,"status" "consent_status" NOT NULL DEFAULT 'PENDING',"approved_at" TIMESTAMP(3),"expires_at" TIMESTAMP(3),"withdrawn_at" TIMESTAMP(3),"document_storage_key" TEXT,"recorded_by" UUID,"reviewed_by" UUID,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "media_consents_pkey" PRIMARY KEY("id"));
ALTER TABLE "media_consents" ADD CONSTRAINT "media_consents_media_id_fkey" FOREIGN KEY("media_id") REFERENCES "education_videos"("id") ON DELETE RESTRICT ON UPDATE CASCADE; CREATE INDEX "media_consents_media_id_status_idx" ON "media_consents"("media_id","status");

CREATE TABLE "health_facilities" ("id" UUID NOT NULL,"name" TEXT NOT NULL,"facility_type" "facility_type" NOT NULL,"region_id" UUID NOT NULL,"district_name" TEXT,"address" TEXT NOT NULL,"public_contact" TEXT,"service_hours" TEXT NOT NULL,"description" TEXT,"latitude" DECIMAL(9,6),"longitude" DECIMAL(9,6),"is_active" BOOLEAN NOT NULL DEFAULT true,"verification_status" "facility_verification_status" NOT NULL DEFAULT 'DRAFT',"verified_at" TIMESTAMP(3),"source_name" TEXT NOT NULL,"is_sample" BOOLEAN NOT NULL DEFAULT false,"created_by" UUID,"updated_by" UUID,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "health_facilities_pkey" PRIMARY KEY("id"));
ALTER TABLE "health_facilities" ADD CONSTRAINT "health_facilities_region_id_fkey" FOREIGN KEY("region_id") REFERENCES "regions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; CREATE INDEX "health_facilities_region_id_facility_type_verification_status_is_active_idx" ON "health_facilities"("region_id","facility_type","verification_status","is_active"); CREATE INDEX "health_facilities_name_idx" ON "health_facilities"("name");
CREATE TABLE "facility_services" ("facility_id" UUID NOT NULL,"service" "facility_service_type" NOT NULL,"verified" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "facility_services_pkey" PRIMARY KEY("facility_id","service")); ALTER TABLE "facility_services" ADD CONSTRAINT "facility_services_facility_id_fkey" FOREIGN KEY("facility_id") REFERENCES "health_facilities"("id") ON DELETE CASCADE ON UPDATE CASCADE; CREATE INDEX "facility_services_service_verified_idx" ON "facility_services"("service","verified");
