import { FormEvent, type ReactNode, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiFetch } from '../../api/client';
import { Button, buttonClassName } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { DataTable, EmptyState, ErrorState, FilterBar, PageHeader, StatCard } from '../../components/ui/patterns';
import { StaleContentDisclosure } from '../../components/pwa/ConnectivityBanner';
type Region={id:string;name:string;type:string};type Stat={id:string;region:{name:string};year:number;period_type:string;period_start:string;period_end:string;data_category:string;count_suppressed:boolean;case_count:number|null;source:string;updated_on:string;is_sample:boolean};type Facility={id:string;name:string;facility_type:string;address:string;public_contact?:string;service_hours:string;source_name:string;is_sample:boolean;regions:{name:string};facility_services:{service:string}[]};const selectClass='field-control text-sm';
export function PublicInformationPage(){
 const[regions,setRegions]=useState<Region[]>([]);const[stats,setStats]=useState<Stat[]>([]);const[facilities,setFacilities]=useState<Facility[]>([]);const[regionId,setRegionId]=useState('');const[year,setYear]=useState('2026');const[periodType,setPeriodType]=useState('');const[type,setType]=useState('');const[service,setService]=useState('');const[q,setQ]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{void apiFetch<{items:Region[]}>('/public/regions').then(r=>setRegions(r.items)).catch(()=>setError('Daftar wilayah belum dapat dimuat.'))},[]);
 const load=async()=>{setLoading(true);setError('');try{const[s,f]=await Promise.all([apiFetch<{items:Stat[]}>(`/public/statistics?limit=50${regionId?`&regionId=${regionId}`:''}${year?`&year=${year}`:''}${periodType?`&periodType=${periodType}`:''}`),apiFetch<{items:Facility[]}>(`/public/facilities?limit=50${regionId?`&regionId=${regionId}`:''}${type?`&type=${type}`:''}${service?`&service=${service}`:''}${q?`&q=${encodeURIComponent(q)}`:''}`)]);setStats(s.items);setFacilities(f.items)}catch{setError('Informasi belum dapat dimuat. Silakan coba lagi.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);const submit=(e:FormEvent)=>{e.preventDefault();void load()};const visibleTotal=stats.reduce((n,s)=>n+(s.case_count??0),0);const max=Math.max(1,...stats.map(s=>s.case_count??0));
 return <main className="mx-auto max-w-7xl space-y-8 px-4 py-6 sm:px-6 lg:px-8">
  <Link to="/" className={buttonClassName({variant:'ghost'})}>← Kembali ke beranda</Link><PageHeader eyebrow="Pencarian tanpa GPS" title="Temukan informasi dan fasilitas layanan" description="Gunakan wilayah dan jenis layanan secara manual. Hanya fasilitas aktif dan terverifikasi yang ditampilkan."/>
  <StaleContentDisclosure />
  <FilterBar onSubmit={submit} className="lg:grid lg:grid-cols-3 xl:grid-cols-6"><Field label="Kabupaten/kota" id="region"><select id="region" className={selectClass} value={regionId} onChange={e=>setRegionId(e.target.value)}><option value="">Semua wilayah</option>{regions.filter(r=>r.type==='CITY_REGENCY').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Jenis fasilitas" id="facility-type"><select id="facility-type" className={selectClass} value={type} onChange={e=>setType(e.target.value)}><option value="">Semua jenis</option><option value="PUSKESMAS">Puskesmas</option><option value="RUMAH_SAKIT">Rumah sakit</option><option value="KLINIK">Klinik</option></select></Field><Field label="Layanan" id="service"><select id="service" className={selectClass} value={service} onChange={e=>setService(e.target.value)}><option value="">Semua layanan</option><option value="COUNSELING">Konseling</option><option value="HIV_TESTING">Tes</option><option value="ARV_SERVICE">Layanan terapi</option><option value="DISABILITY_ACCESS">Akses disabilitas</option></select></Field><Field label="Nama fasilitas" id="facility-q"><Input id="facility-q" value={q} onChange={e=>setQ(e.target.value)} maxLength={80} placeholder="Ketik nama"/></Field><Field label="Tahun data" id="year"><Input id="year" inputMode="numeric" value={year} onChange={e=>setYear(e.target.value.replace(/\D/g,'').slice(0,4))}/></Field><Field label="Periode data" id="period"><select id="period" className={selectClass} value={periodType} onChange={e=>setPeriodType(e.target.value)}><option value="">Semua periode</option><option value="MONTHLY">Bulanan</option><option value="QUARTERLY">Triwulanan</option><option value="SEMESTER">Semester</option><option value="YEARLY">Tahunan</option></select></Field><Button type="submit" disabled={loading} className="xl:col-span-6">{loading?'Memuat…':'Terapkan filter'}</Button></FilterBar>
  {error?<ErrorState description={error} onRetry={()=>void load()}/>:null}
  <section aria-labelledby="facilities-title"><p className="eyebrow">Layanan terverifikasi</p><h2 id="facilities-title" className="mt-1 text-2xl font-bold">Fasilitas yang dapat dipilih</h2><p className="mt-2 text-sm text-slate-600">Hasil berdasarkan filter manual Anda. Lokasi perangkat tidak digunakan.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{!loading&&facilities.length===0?<div className="md:col-span-2"><EmptyState icon="building" title="Belum ada fasilitas sesuai filter" description="Coba perluas wilayah, jenis fasilitas, atau layanan."/></div>:facilities.map(f=><Card key={f.id}><CardHeader><CardTitle>{f.name}</CardTitle><p className="text-sm text-slate-500">{f.facility_type.replace('_',' ')} · {f.regions.name}{f.is_sample?' · DATA UJI':''}</p></CardHeader><CardContent><dl className="grid gap-3 text-sm"><Detail label="Alamat publik">{f.address}</Detail><Detail label="Jam pelayanan">{f.service_hours}</Detail><Detail label="Layanan terverifikasi">{f.facility_services.map(x=>x.service).join(', ')||'Belum dicatat'}</Detail><Detail label="Kontak resmi">{f.public_contact||'Belum tersedia'}</Detail></dl></CardContent></Card>)}</div></section>
  <section aria-labelledby="stats-title"><p className="eyebrow">Data publik</p><h2 id="stats-title" className="mt-1 text-2xl font-bold">Informasi agregat</h2><p className="mt-2 text-sm text-slate-600">Nilai kecil disembunyikan untuk membantu melindungi kerahasiaan.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><StatCard label="Baris terpublikasi" value={loading?'—':stats.length} icon="clipboard"/><StatCard label="Total nilai yang boleh tampil" value={loading?'—':visibleTotal} description="Tidak termasuk sel yang disembunyikan." icon="activity"/></div><div role="img" aria-label="Grafik batang jumlah kasus agregat; nilai disuppression dijelaskan dalam tabel" className="mt-5 space-y-3">{stats.map(s=><div key={s.id}><p className="text-sm text-slate-600">{s.region.name} — {s.data_category}</p><div className="mt-1 h-6 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand" style={{width:s.count_suppressed?'12%':`${Math.max(12,((s.case_count??0)/max)*100)}%`}}><span className="sr-only">{s.count_suppressed?'Nilai disembunyikan':`${s.case_count} kasus`}</span></div></div></div>)}</div><div className="mt-5"><DataTable caption="Tabel alternatif informasi kasus" rows={stats} rowKey={s=>s.id} empty={<EmptyState title="Belum ada data sesuai filter" description="Ubah tahun, periode, atau wilayah untuk mencoba kembali."/>} columns={[{key:'region',header:'Wilayah',render:s=>s.region.name},{key:'period',header:'Periode',render:s=><>{new Date(s.period_start).toLocaleDateString('id-ID')}–{new Date(s.period_end).toLocaleDateString('id-ID')}</>},{key:'category',header:'Kategori',render:s=>s.data_category},{key:'count',header:'Jumlah',render:s=>s.count_suppressed?'Data tidak ditampilkan untuk melindungi kerahasiaan.':s.case_count},{key:'source',header:'Sumber',render:s=><>{s.source}<span className="block text-xs text-slate-500">Diperbarui {new Date(s.updated_on).toLocaleDateString('id-ID')}</span></>} ]}/></div></section>
 </main>}
function Field({label,id,children}:{label:string;id:string;children:ReactNode}){return <div className="min-w-0"><Label htmlFor={id}>{label}</Label><div className="mt-1.5">{children}</div></div>}
function Detail({label,children}:{label:string;children:ReactNode}){return <div><dt className="font-bold text-slate-500">{label}</dt><dd className="mt-1">{children}</dd></div>}
